### ISSUE TITLE
In JMM Server use a OK button to close after entering initial details

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/jmmserver#10]
**Reported by werndlymob, May 6, 2012**

In the Initial Setup window where you enter... erm, some data (I forgot what), there should be an OK button to confirm the change. I remember there was a filed to enter something and the button to Test the value (a login perhaps?). After you successfully passed the test, you had to close the window with a red X on the top right. I think it would be more Windows-like to include an OK button to accept the changes and close the window.

**Comment by ElementalCrisis** [comment]
Included in https://github.com/japanesemediamanager/jmmserver/commit/077fabd99e4dc69956b3d3d64e7a852fbad7b650.
