### ISSUE TITLE
18 Restricted Series don't appear in Calendar anymore?!! (BUG!?)

### ISSUE THREAD

**Issue by misakitchi** [japanesemediamanager/jmmserver#104]
I don't see the 18+ series in calendar anymore?!!
Not in Calendar and not in filters?! :(

**Comment by jmediamanager** [comment]
Can you check if the following settings is enabled

JMM Desktop - Settings - AniDB
"Automatically Update Calendar"

**Comment by misakitchi** [comment]
I don't know how but now i can see 18+ series on calendar, but not all... only some...
And yes "Automatically Update Calendar" is on 24h

![Uploading JMM Calendar.jpg . . .]()

For calendar option i put 100days.
There is a gap between "Sengoku Musou" (12/01/15) and "Hitsugi OAV" (10/03/15) see screenshot

And i still use v3.1.25.0 because 100% CPU bug... so calendar bug is a little bug, if you can do something for the big bug 100% CPU i prefere :)

**Comment by jmediamanager** [comment]
It could be related to this bug on AniDB
https://github.com/japanesemediamanager/jmmclient/issues/75

**Comment by jmediamanager** [comment]
Confirmed now working for me.
