### ISSUE TITLE
crashes on file hash in 3.4.2.8?

### ISSUE THREAD

**Issue by AreFinstad** [japanesemediamanager/jmmserver#109]
having problems with the JMM server stops responding when hashing some new files here.
once i remove the file in question then it would work fine again till another file showed up (i had 7 so far, all of which checked out with JDownload with the CRC when i downloaded it from my Seedbox aswell as the AniDB online Java Client (hosted the files in question in my Mega folder aswell, just in case))

the issues are on the 22th-24th of November 2014.
Logs and Files: https://mega.co.nz/#F!JsJxUKQD!kaUdPc5vx_yUZ0nxidsrSQ

**Comment by jmediamanager** [comment]
Should be fixed in 3.4.3.2
