### ISSUE TITLE
Cannot hash files or folders with Unicode characters such as ★ or ⁄

### ISSUE THREAD

**Issue by Revenger1589** [japanesemediamanager/jmmserver#110]
The server won't hash folder or files that contain unusual characters. Example:
Black★Rock Shooter
Fate ⁄ Zero
. hack⁄⁄Quantum

**Comment by jmediamanager** [comment]
MySQL on Linux has this issue, but for different reasons.

See the following link
https://mathiasbynens.be/notes/mysql-utf8mb4

To solve I had do do the following
- Set collation to utf8mb4_unicode_ci with a CHARACTER SET of utf8mb4 
- Change the connection string in JMM server to also specify the character set above.

(in progress)

**Comment by jmediamanager** [comment]
See her for reference
http://stackoverflow.com/questions/6692947/how-to-set-encoding-in-fluent-nhibernate

**Comment by jmediamanager** [comment]
Further reference
https://mathiasbynens.be/notes/mysql-utf8mb4

**Comment by teohhanhui** [comment]
Good to see another convert to utf8mb4 (the "real" UTF-8 encoding in MySQL)
