### ISSUE TITLE
Second series  of a anime

### ISSUE THREAD

**Issue by saitoh183** [japanesemediamanager/jmmserver#114]
I have noticed that second series of animes tend to have the synopsis of the first series. For example SOA and SOA2, all the episode of SOA2 have the SOA1 synopsis even if the episode title is proper. Im guessing this is because of TVDB being the information source.

I have my SOA and SOA2 set up as \\SRV-SAITOH\Videos\Anime\Sword Art Online\Season 01 and \\SRV-SAITOH\Videos\Anime\Sword Art Online II\Season 01

This only plagues anime that have second series and tvdb adds those series as season 2

A few i have : Log Horizon, Jormungand, Black Lagoon

**Comment by jmediamanager** [comment]
It won't pick this up unless it is fund in the community recommendations
