### ISSUE TITLE
Update Trakt API to version 2.0

### ISSUE THREAD

**Issue by AreFinstad** [japanesemediamanager/jmmserver#116]
with the new "2.0" update of the Trakt site also comes with a huge rewrite of the api and other things,
think we need to take a look at this again for the best support. 

https://medium.com/@trakt/announcing-trakt-tv-2-0-83179ce1eda0
http://docs.trakt.apiary.io/

**Comment by RickDB** [comment]
Authentication for Trakt (and maybe other things) is currently not working with JMM server 3.4.2.6, possible related to them switching to OATH.
So it's not working with V1 at the moment, a lot of things were dropped for the current V1 so there's no real legacy support which is why everyone is forced to use V2 as the Trakt developers aren't giving a grace period to update apps.

**Comment by jmediamanager** [comment]
I'll take a look at this in the next few days

**Comment by CatmanIX** [comment]
Yeah, even if they say the V1 API is still supported, it's not really working. It can still figure out how to connect series to trakt (though it's a bit malfunctional doing that too) it's not actually very useful since it can't push any watched states or anything else to trakt.

All it really accomplishes is retrieving posters and stuff from trakt, which are all the same as TVDB's anyway.

**Comment by OzWookiee** [comment]
Just tried to setup Trakt login on JMMDesktop and am getting "failed authentication" errors. Works fine when I setup trakt in plex (independent of JMM)

**Comment by OzWookiee** [comment]
Just tried to setup Trakt login on JMMDesktop and am getting "failed authentication" errors. Works fine when I setup trakt in plex (independent of JMM)

**Comment by jmediamanager** [comment]
Yes, Trakt in Plex is not related to JMM

**Comment by OzWookiee** [comment]
Yup, just to illustrate that I'd used the right credentials :)

**Comment by CatmanIX** [comment]
Any chance of this being fixed anytime soon? We've had a couple of version updates since trakt's change and it still hasn't been worked out.

I wouldn't think an API change would require all the much work to sort out, but maybe it's more drastic than i thought?

**Comment by jmediamanager** [comment]
It is a massive change unfortunately.
The Trakt moderators don't respond to my emails about giving me access to the other type of access either, so not promising

**Comment by jmediamanager** [comment]
Just a quick update...

I am finally working on this, and have gotten the authorization working, but still quite a bit of work to do.

**Comment by CatmanIX** [comment]
Thanks, good to know! Hope you don't have too many troubles with it.

Relatedly, do you think when that's fixed you could add a "Has Trakt Link" group filter to make it easier to find groups that need to be updated after the fix is released?

**Comment by jmediamanager** [comment]
Ah yup that can be done if you submit a new issue?

**Comment by CatmanIX** [comment]
Sure: #153

**Comment by jmediamanager** [comment]
Server side work is mostly done

**Comment by jmediamanager** [comment]
Umm still going on this one.
If anyone is interested in testing out the beta version of this please let me know.

Also feel free to follow me on Trakt
https://trakt.tv/users/lwerndly

**Comment by AreFinstad** [comment]
as always i would like to test the beta

**Comment by jmediamanager** [comment]
Ok,
l will be running it on my home machine for the next few days to make sure it doesn't completely destroy Trakt data, after that I'll post the beta here

**Comment by AreFinstad** [comment]
fair enough. i mean how bad can it mess up trakt? i dont mind manually editing for corrections if something is wrong TBH. im fine with it. will ofc report if it doesnt work correctly XD

**Comment by jmediamanager** [comment]
My first attempt actually removed everything that wasn't in JMM (which meant all other movies and tv shows)

But should be some time next week (once the to do list for Trakt drops below 10 items or so)

**Comment by AreFinstad** [comment]
wow, didnt think it would be that bad...... yeah, feel free to test that out yourself for now XD will ofc test once you feel secure with it. loosing everything is a "bit" too much..... esp when you got almost everything you ever watched (that i can remember) on that site.

**Comment by AreFinstad** [comment]
thought: could we have a button that checks our Trakt history? (the last week or last month for example) and then marks things as watched within those times, that way we dont have to sync each series and everything will go smoother aswell as its just one button for everything.

also, watchstates when Synced from say Trakt should also be synced with AniDB, MAL and so on aswell IMO.

**Comment by jmediamanager** [comment]
For those interested in trying out the beta, you can download it here
http://www.jmediamanager.org/latestdownloads/beta/JMM_Beta_3.4.4.1.zip

And here is some information on the changes
http://japanesemediamanager.github.io/changes/3.4.4/changes344.html

**Comment by misakitchi** [comment]
Hi!
Thanks for JMM Server update! :)
I don't understand the benefit of using Trakt TV... somebody can explain me?
For episode preview i have TvDB: i only need that...
What have more Trakt TV?
Thx!

**Comment by CatmanIX** [comment]
Trakt is for tracking what shows you've watched, like MAL, but not focused on anime.

**Comment by jmediamanager** [comment]
Yeah Trakt adds a more social element

You can add you own comments, follow your friends etc
I will be adding Trakt comment support to episodes soon as well
As well as thing like "262 people" wathc this show today etc

**Comment by misakitchi** [comment]
OK so its only for "Social Element"?
My computer is very old so i put only the minimum! If trakt TV add more memory/cpu i will not use it...
But Thx i will think on it :)

**Comment by jmediamanager** [comment]
Yeah don't bother unless you are interested in Trakt
I did add a couple of things for people who use the Metro dashboard (me)

**Comment by AreFinstad** [comment]
im loving the new metro screen, only one thing tho..... i dont use the metro darshboard (as the cover wall)
could we have a way for us to open the metro series view from the normal dashboard (as its easier to manage with its scroll bars and such instead of just random things IMO)

and i REALLY love the new community data tab (just <3 ) 
its just one thing tho........ i have a large H Collection aswell that is handled by JMM, all of these show up on this tab and is making it a mess as they are not on tvdb or trakt (except a weird few)
would be great if we can either ban a tag, custom tag (in my case as i tag everything myself with these).
ATM the community tag is going through 1271 groups, and almost 600 of them is H content (because of its mostly just one or two files per group)

**Comment by AreFinstad** [comment]
posting another message incase someone read my original comment and not all the edits XD (just in case)
will delete this message once the admin and others read this.

**Comment by jmediamanager** [comment]
Hi I'll summarize here, usually it is best to raise issues foe each new item, otherwise they will get lost in the comments like this

1. Yup please raise an issue for this
2. This can't quite be done, bcoz if the link is wrong it actually means we couldn't find it on Trakt at all
3. New issue
4. Yup this is already on my internal to do list, that's the reason it is done as tabs
6. Yes it used to have avatars for your friends, but Trakt has removed this functionality from their AI now :(
Comments on spoilers is also on my to do list
7. Characters is on my to do list
8. New issue - will look at docking the top toolbar

**Comment by AreFinstad** [comment]
@ EDIT 2: well, not sure if the Trakt API supports this. but cant JMM download a list of ALL series and movies that is in your Trakt account and Compare them? it could compare it to itself, or ANIDB/MAL and other things.
that way it could give the user a list of all the things that isnt right with that picture.
something like that could also have a block list where the user can enter series and movies that they dont want to show up on the list (like normal shows and movies that you want to keep on Trakt.)

but i guess all that is a bit of hassle when the user CAN just look though all his pages and remove it that way.

**Comment by AreFinstad** [comment]
Issues:
1: https://github.com/japanesemediamanager/jmmclient/issues/189
3: https://github.com/japanesemediamanager/jmmclient/issues/190
8: https://github.com/japanesemediamanager/jmmclient/issues/191


other thoughts on the new changes: how do you feel about the old Dashboard being able to open the Metro Series View, i for one would love it this way as the Cover Flow Style is too random in my Taste.

**Comment by jmediamanager** [comment]
Regarding EDIT 2 above, I can't do a full reconciliation like that because Trakt is used by other HTCP apps like MediaPortal and Kodi, to track movies and other tv shows.
I can't just assume everything is related to JMM and anime.

With the dashboard opening the metro series view, yes I already plan to change the series view so that by default it will look like the metro view.
There will be a button to switch back and forth between the metro view and the detail view.

**Comment by AreFinstad** [comment]
yes, thats why we can have an ignoring list. im aware that other program use Trakt aswell, i use Trakt ALOT more for that stuff than Anime ATM. 

also nice to hear that we are getting a change there..... and with the later added character support it will be perfect :D

**Comment by jmediamanager** [comment]
Preview of character section

![snap1](https://cloud.githubusercontent.com/assets/6645153/9346045/eef730b6-465a-11e5-8e8a-a7237be5abe5.jpg)

**Comment by AreFinstad** [comment]
looks good, but it looks like it can get a bit messy. does it sort by number of episodes they are in for example or are they just random?
also, will we get a deeper view of them aswell? like either being able to click them and it will open the AniDB page about them, or have JMM have its own page with the same info (ish)?

**Comment by jmediamanager** [comment]
It always shows the Main characters first.
The main characters as you can see above are shown with more info.
However if you hover over any of them it will show you the full info that is available from AniDB.

But there is really no other information available from the API other than what is shown above for the main character

**Comment by AreFinstad** [comment]
yeah, the amount of info we get depends on the character pages themself on AniDB, which is fair obv. 
so when you are saying "full info that is available from AniDB." do you also mean character tags? because that is something JMM does not have yet as far as i know after the large tag change they did a while ago.

**Comment by AreFinstad** [comment]
hmmmmm i thought a bit on this, in the Community Data Tab ATM we have an option called: Automatically remove bad information from the database.
what if we could have a list of all of those and have either links to their Trakt page (so we can remove them there) or have a button on the list on a per series basis that removes its watchstate and collection state from Trakt. 

with time and once the mod controlled linking is in it will be more flawless.

**Comment by jmediamanager** [comment]
Hi @AreFinstad please send me an email at 
jmediamanager@gmail.com

**Comment by AreFinstad** [comment]
im unsure why you would want me to send a mail to you.... i did tho.

**Comment by maxpiva** [comment]
Leo, seems trakt is working, only problem, found so far, seems movies are filtered out in search (link search), example: The Garden of The Sinners: Future Gospel, trakt: http://trakt.tv/movies/the-garden-of-sinners-future-gospel-2013.

**Comment by jmediamanager** [comment]
Yeah, I still don't properly support movies yet.
The API actually has a different method for searching movies etc

**Comment by bigretromike** [comment]
API still dont support 'movies' I probably try to add that if now one is willing because that breaks alot of cross-links and scroobing.

**Comment by ElementalCrisis** [comment]
There is support for movies, I have them in my collection and they have links to The Movie DB which is what JMM uses for movies as TvDB doesn't allow them. 

There could be some work done for movies though like using the fanart/poster for the "episode" image and using the description for the "series" for the episode description.

**Comment by bigretromike** [comment]
JMM wont give you proper id/name for those Movies.

**Comment by ElementalCrisis** [comment]
Ah, I did not know that.
