### ISSUE TITLE
SYD* OAD & Maken-ki! Two OVA problems.

### ISSUE THREAD

**Issue by celcius01** [japanesemediamanager/jmmserver#120]
Hey guys,
Well... i don't know how to describe this so i'll just show you:
![maken-ki two oad](https://cloud.githubusercontent.com/assets/9668999/5695532/738d9fe2-99e3-11e4-8785-0663045ac520.png)
![syd oad](https://cloud.githubusercontent.com/assets/9668999/5695534/792cd99a-99e3-11e4-979e-e239fcaf085f.png)

1. Both were marked as watched even though i haven't touched them.
2. And when i want to switched them back to unwatched, surprise surprise all i got was emptied list of episodes.
3. I've searched all my collections (500+ of them) and only these two have this problem.

Any ideas?
Thanks

**Comment by AreFinstad** [comment]
could you atleast upload a log so we can have a look at them?

**Comment by celcius01** [comment]
Uh... what kind of log do you want? I just exported my 'All' log and it got around 10000 lines. I'm pretty sure you don't want that one.

**Comment by AreFinstad** [comment]
you can just upload the log text file to a file host like mega.co.nz /google drive / one drive / dropbox

you will find the logs in the install folder, you can upload the last few days of logs for both the desktop and server just in case (unless the bug started before that) 

you should upload the hole files as they contain all the lines, you should also either have them renamed or sorted in folders per program fro the admin to know what he is looking at. 
i recommend having one folder for the server logs and one for the desktop logs like this: 
https://mega.co.nz/#F!NlYhnR4I!AUceiRgrwleJ69hwHXvXRQ

**Comment by celcius01** [comment]
Thanks. Uploading the logs now. 
Wait does this mean i'm the only one with this problem?

**Comment by celcius01** [comment]
Here you go:
https://www.dropbox.com/sh/7073vwajocku282/AABtONkh_bc-UjcxxIJQNmgoa?dl=0

I recently renewed my laptop and the transfer for jmm started on the 20th Dec 2014. Everything was rehashed that day. So if you wanna look, probably best to start there.
The same problem happened to maken-ki even on my old machine since last year, and i only noticed the problem for SYD today.

**Comment by AreFinstad** [comment]
well i dont recall an issue that is like this on this site soooo, you might just be the one. 
not really sure as im not a dev and i just give input and report bugs and such on my own.

the admin and the other devs would want the logs in either case tho so you should always upload them if you can

**Comment by jmediamanager** [comment]
Hi @celcius01, Could you please do the following.

1) Stop jmm server and desktop
2) Rename your current day log files to something like (.bak)
3) Start jmm server and desktop
4) Get to the point in JMM Desktop where you see the weird rendering errors
5) Stop jmm server and desktop
6) Upload those current day log files

Also just a note - I can see you are using version 3.1.32.0, we are no longer supporting the current official version, any bug fixes will go into the beta
(Hopefully 3.4 official isn't too far away)

**Comment by celcius01** [comment]
Hi Leo,
Here they are:
https://www.dropbox.com/sh/zzetumv065y9mmg/AAAyNuJOKEFzYbW6fLXlKIUca?dl=0

The .bak files are the original for today, and the rest are from direct navigating to the problem series.
Hmm i really thought this is a common problem, because it happened to me on my last machine too.

**Comment by celcius01** [comment]
Speaking of beta, i tried it today and it's not updating to 3.4.2.9. I still got the 3426 version. When i clicked the tick mark it says that i have the latest version. Any ideas?

**Comment by jmediamanager** [comment]
3.4.2.6 is the latest for JMM Desktop
3.4.2.9 is the latest for JMM Server

**Comment by celcius01** [comment]
Tada! 5 seconds ago.
![jmms 3426](https://cloud.githubusercontent.com/assets/9668999/5730559/16a32354-9bb6-11e4-8d94-e94ca01f1fb9.PNG)

**Comment by jmediamanager** [comment]
Even when you press the 'Check for Updates' button?

If that doesn't work you can try downloading the latest version, and manually extracting the files
http://www.jmediamanager.org/jmmserver/jmmserver.all.to.3.4.2.9.zip

Although I doubt it it will fix your particular issue
http://japanesemediamanager.github.io/changes.html

**Comment by jmediamanager** [comment]
Also I will be releasing 3.4.2.10 some time today.

And I did look at your logs, and can't seem to find any issues.
Is it possible to get a copy of your database?

**Comment by celcius01** [comment]
3.4.2.10 today? Nice! 
Yes, the image i gave is directly after i pressed the check for updates. Oh btw i don't know if this is any help but i try to press unwatched just now and i got this:
![mk2](https://cloud.githubusercontent.com/assets/9668999/5731222/3616f372-9bbc-11e4-8eea-35f6a3796093.PNG)

Sorry, i don't think that will help much...

And one other thing, i got this for a while now and it's becoming an eyesore:
It showed that i got 2 missing episodes, but i got all 5 episodes of it and it doesn't have any specials:
![syd](https://cloud.githubusercontent.com/assets/9668999/5731301/fcafb5a0-9bbc-11e4-9dbd-fcc42b70ef57.PNG)

Highlighting the red exclamation mark says that i'm missing the episodes from the group i'm collecting, which is not true because all the episodes are from one group only:
![syd 2](https://cloud.githubusercontent.com/assets/9668999/5731368/81d67eda-9bbd-11e4-9f05-fad272d8a087.PNG)

Oh, and here's my db. You meant the backup, right?
https://www.dropbox.com/s/kb5hikvv0v3fv33/JMMServer.bak?dl=0

**Comment by jmediamanager** [comment]
Yup just released 3.4.2.10.

I have finished downloading your database, so you can remove it now if you like.
I will try it out today.

**Comment by celcius01** [comment]
Thanks~

**Comment by jmediamanager** [comment]
Ok @celcius01, I found the issue.
I can see the same in my collection, although I don't get the weird rendering errors that you do.

Basically this was caused by AniDB switching episode ID's around between the two OVA's.
You will see that on the second OVA the episode type combo box is empty.

To resolve the issue, do the following.

- Click the 'Delete Series' button on the first OVA (make sure NOT to delete physical files)
- Click the 'Delete Series' button on the second OVA (make sure NOT to delete physical files)
- Click the 'Run Import' button on the Server tab
- Wait until it has finished

This will re-create both OVA's with the proper episode information.

I will look at your other issue soon

**Comment by jmediamanager** [comment]
Ok the 2nd issue looks similar to the first.
It looks like episodes were re-assigned from one series to another (from 8204 to 10761)

If you delete the series, and re-create them again it should work.

**Comment by celcius01** [comment]
Mama mia, Leo! Time and time again you saved me! If we are to play co-op on any games someday, i'll be sure to cover your rear! 
Thanks alot man! You are magic.
How'd you find out anyway? If it's not too technically difficult for you to explain and if you don't mind.

**Comment by maxpiva** [comment]
I you don't mind Leo...

anidb.net is not failproof, since it's crowdsourced, sometimes, episodes
are moved, renamed, etc by ops. If you indexed the episode in question
before the change is made, JMM doesn't get notified of the change.
then, JMM DB will be not in SYNC with anidb.net...
Currently anidb.net send private messages when such changes exists.

We talked about that long ago with Leo, and we concluded that a change is
needed in the ANIDB public API to JMM identify and correct the episodes
automagically without disrupting anidb.net site message system.

**Comment by jmediamanager** [comment]
@celcius01 nothing too complicated, just noticed from your screenshot that you were missing the episode type information.
I tried using the 'Update AniDB Info' button to force download the information again.
When you do this, you see the error message in the JMM server logs.
After that it is sifting through the database and trying to match it up against what is on AniDB

@maxpiva Yup I will follow this up again with the AniDB devs to see what they can do.
