### ISSUE TITLE
Local files and Anidb mylist not synched.

### ISSUE THREAD

**Issue by celcius01** [japanesemediamanager/jmmserver#121]
Specifically, Mirai Fukuin & Extra Chorus, and Mojokko Shimai no Yoyo to Nene (with its special).
These 4 were the few of the latest ones being downloaded, and they are not shown in my anidb mylist. I just noticed this today.
All checked for crc, nothing wrong with them. As per my torrent history, all 4 of them were the last ones being downloaded, but according to my folder details, the last ones being downloaded were another 2 more series. I don't know which one finished first...
I already tried deleting the series and then run import again, nothing. 
JMMD server tab > sync anidb mylist > nope. 
JMMS > sync mylist > still nope. Funny thing about this step though, no matter how many times i click 'sync mylist', it will always show that 177 items in queue. After a few minutes, it reduced to 0 immediately. This was the last thing i did to jmms. Here's a pic:
![jmms 177](https://cloud.githubusercontent.com/assets/9668999/5767177/f7661c3e-9d41-11e4-8382-431fc97e4c25.PNG)

I didn't change any settings or anything btw. I download tons of series at a time, and they all showed up nicely in mylist.
Logs here:
https://www.dropbox.com/sh/h4inyqufkoq71i8/AAAx4xNDu2IUw_grNw040_uTa?dl=0

**Comment by jmediamanager** [comment]
Can you post a screenshot of how your mylist settings look.
This is mine

![snap6](https://cloud.githubusercontent.com/assets/6645153/5769520/fd24cb3c-9d70-11e4-88fb-bf3acac802f0.jpg)

**Comment by celcius01** [comment]
Like this?
![jmmd settings](https://cloud.githubusercontent.com/assets/9668999/5771716/2fdbc5fa-9d7e-11e4-8fa3-ec5449a274c5.PNG)

**Comment by celcius01** [comment]
Now confirming that all my recently downloaded anime is not synching with anidb mylist. Just downloaded 3 new series and it's not showing green in anidb.
Speaking of synching, MAL is not being updated too and pressing 'Download Watched States from MAL' in server tab of JMMD does nothing. "Process is Queued" dialog came but that's it, queue command reads 0 all the time.

**Comment by jmediamanager** [comment]
Ok for the AniDB stuff, can you do the usual thing of clearing the JMM server logs
And then try marking an episode as watched
And then send me those logs

**Comment by celcius01** [comment]
Marking an episode of the new animes right? Doing it now.

**Comment by celcius01** [comment]
Here's the log folder. I've uploaded the fresh log after clicking watch on the new anime. The backup is also there. You wanted JMMS only right?
https://www.dropbox.com/sh/v184wuxwecnk3rm/AABJkQXfpxCNRDj6feD9drEPa?dl=0

**Comment by celcius01** [comment]
Whoa i just read the log file and it seems that it started adding mylist entry after i click watch. And it only add that episode. I've confirmed it in anidb, only that episode was added after clicking watch.

**Comment by jmediamanager** [comment]
yeah, I think you may have had some temporary issues (shown by these log entries)
411 NO SUCH MYLIST ENTRY

When you get that type of error it menas that it expected the file to be on AniDB, but it wasn't
So it then added it, and mark it as watched

**Comment by celcius01** [comment]
First time this happened was on the 14th Jan, that day around 7 series/movies was being downloaded and 5 managed to get through before Mirai Fukuin & the other one got ignored. Timing from the folder detail was around 02:30am, and the 1st one to be having this problem is Majokko Shimai. I tried looking at the log on that day, and my limited knowledge of reading what was there failed me.

**Comment by celcius01** [comment]
Decided to reinstall the stable version of both server & desktop just now, and all's right with the world. Files are being added nicely and MAL is getting updated now too. Must've been some kind of hidden bug or something.
