### ISSUE TITLE
MAL watched states

### ISSUE THREAD

**Issue by Eagle97** [japanesemediamanager/jmmserver#122]
For me if I take and sync watched states from MAL using the option provided it doesn't seem to do anything. And also I wonder if it is possible to have generic files an example is.

If you have watched Akame Ga Kill 10/24 episodes and missing like episode 15 it will say that there is 13 unwatched even though there should be 14.

**Comment by ElementalCrisis** [comment]
Fixed in 3.6

https://github.com/japanesemediamanager/jmmserver/pull/332#event-734683616
