### ISSUE TITLE
Minimize problem

### ISSUE THREAD

**Issue by Eagle97** [japanesemediamanager/jmmserver#124]
For example when JMM Server goes to minimized and is in the taskbar I seem to have a problem, that if you minimize it and then try to open it before it gets minimized it will be unresponsive and you can not close the window and have to restart the process. Attached picture.
![bug11111](https://cloud.githubusercontent.com/assets/1307729/5889789/e8eae25e-a438-11e4-87f2-89e69863438e.JPG)

To replicate press your JMM Server icon fast and then check what happens. I think a fix for this would be have the option for it to stay in the taskbar after being minimized instead of appearing in right bottom corner.

**Comment by Eagle97** [comment]
It is possible to fix by minimizing again and doing show, just figured that out. But I think there should be a solid solution.

**Comment by misakitchi** [comment]
You have windows8?

**Comment by Eagle97** [comment]
Yes windows 8.1 pro x64

**Comment by ElementalCrisis** [comment]
[2016-07-25_02-15-33.zip](https://github.com/japanesemediamanager/jmmserver/files/381103/2016-07-25_02-15-33.zip)

Can reproduce, here's a video if it in action. Note though that JMM Server is still usable by right-clicking on the icon and clicking show.

**Comment by hidden4003** [comment]
I am unable to reproduce, program icon vanishes from task bad as soon as window is minimized. Any specific setting I am missing? I am using Windows 10.

**Comment by hidden4003** [comment]
Fixed.
