### ISSUE TITLE
Banned from AniDB! (504 CLIENT BANNED)

### ISSUE THREAD

**Issue by misakitchi** [japanesemediamanager/jmmserver#132]
Since one week i m banned from AniDB :'(

in log file the last lines are:

Info|BackgroundWorker.OnDoWork => CommandProcessorGeneral.workerCommands_DoWork => CommandRequest_ProcessFile.ProcessCommand Processing File: 4069
Info|AniDBHelper.Login => AniDBCommand_Login.Process => AniDBUDPCommand.ProcessCommand ANIDB_UDP_COMMS socketResponse: 504 CLIENT BANNED

Info|BackgroundWorker.OnDoWork => CommandProcessorGeneral.workerCommands_DoWork => CommandRequest_ProcessFile.ProcessCommand Processing File: 4070
Info|AniDBHelper.Login => AniDBCommand_Login.Process => AniDBUDPCommand.ProcessCommand ANIDB_UDP_COMMS truncated socketResponse: 555 BANNED
Haywire

JMM Server is v3.1.25.0

I really need help! Thx! :)

**Comment by jmediamanager** [comment]
you need to upgrade to the latest version
http://japanesemediamanager.github.io/downloads.html

**Comment by misakitchi** [comment]
I want but i can't! Because of the 100% CPU bug i have with earlier version... :(

**Comment by AreFinstad** [comment]
an AniDB ban is noting to worry about with JMM really. you prob just got a 6-12 hour ban if its your first time, maybe a 24h one. hardly a big deal. 

this ban still happens if you queue too many commands at once sadly :/

been banned aton of times from JMM and i still use my one account on AniDB. you have to do something REALLY bad to really get banned, this is more of a kick really.

**Comment by AreFinstad** [comment]
if you dont want to use a newer version you have to not let JMM access AniDB in anyway, meaning you have to stop it from using the site all together for half a day or more. if you access the site earlier from when the ban time you have on your account then it will prob increase your ban time.

best cause of action is just to turn off the server for a day and do something else, also might have to pause from time to time in the site accesses when you start to use it again.

**Comment by misakitchi** [comment]
I launch the last version of JMM v3.4.2.19 and no ban with this version
But i still have the 100% CPU Bug... :(

**Comment by misakitchi** [comment]
Why AniDB is banning this version now? Can someone do something about that and unban old version?
Or can we change the version when we ask AniDB API?
Because i can't use the new version with my CPU at 100%... :(

**Comment by AreFinstad** [comment]
the reason you got banned with JMM is that you accessed the AniDB site too many times in a row/too fast. this happens on the old versions where the timing isnt correct or if you use the AniDB site in your browser at the same time as JMM.

an AniDB ban is times and its only a matter of time before you can use your old version if that is what you want.

ofc using JMM that gets the banned message just gives you a longer ban time like i stated above, you can really use it till the ban is over, and you dont know when its over either. try to use it every 12 or 24h and it will prob be fine, leave JMM on will make it try and try again even if you pause the work loads, only way to really be sure is to just have the server off.

**Comment by misakitchi** [comment]
I don't think my account is banned because when i use v3.4.2.19 (the latest) i m not ban...
And i use the "old" version since long time and i m not ban... it must be a new rules in AniDB for old JMM Server :(
When we send command in the AniDB API, there must be version of our JMM Server and aniDB must ban the version < 3.1.xx

**Comment by jmediamanager** [comment]
The ban is because I have disabled the old version of the API client.
I have re-enabled it for now, but this is only temporary
3.1.x.x uses the old host, and I can't afford to keep paying it forever.

I will think about how to solve your problem next week

**Comment by misakitchi** [comment]
OK thanks!
But i don't understand a thing: anidb request pass by your server? its not directly to anidb?
My JMM Server => Your Server (?!) => AniDB Server

**Comment by AreFinstad** [comment]
alittle off topic here, thought to try Patreon ( https://www.patreon.com ) for your server fees? i would love to help out here and im sure more will aswell (there got to be alot more people using this program over who comments on it!)

**Comment by jmediamanager** [comment]
@misakitchi This is how it works

On AniDB, there is an API version
3.4.2.19 uses v2 of the API
Anything lower uses version 1

with my web cache, anything lower than 3.4 uses the old web cache
3.4 or higher is using the new web cache

So basically I am disabling v1 of the AniDB API to force people onto the latest version of JMM

@AreFinstad I'll try to avoid any sort of donations while I can

The old web host is costing me about $15 USD a month
The new web host (Microsoft Azure) costs me nothing at the moment, as it comes bundled with my MSDN subscription
Once it gets above a certain level, I would need to start paying though.

**Comment by misakitchi** [comment]
OK so if i disable all web cache features, my JMM v3.1.x will use directly AniDB API v1 and not your web cache.
But why AniDB ban me?

**Comment by AreFinstad** [comment]
AniDB bans you for overusage of their servers, simple as that.

**Comment by jmediamanager** [comment]
No, this is a 504 Ban, which means the API has been disabled

**Comment by AreFinstad** [comment]
yes but does you not get that ban from overusage of the api?

the old JMM got me banned like 3 times a week from overusage of their api, a limit they set so the servers remain stable prob.

**Comment by jmediamanager** [comment]
Yes that is a different type of ban, not the one @misakitchi is getting

**Comment by AreFinstad** [comment]
i see, im sorry then.
oh well.

**Comment by AreFinstad** [comment]
on a side note, while i have you here.
ever thought about splitting up the access queues from different sites? like one queue for AniDB, one for MAL, one for Trakt/TVDB and so on?

also find it all to be slow and sluggish since it can only do one thing at any given time (like when the Trakt servers are down it uses forever to try accessing those servers eventho they are down)

**Comment by jmediamanager** [comment]
Yes we used to have that, but sqlite cannot handle multi-threaded database access.

Whne we looking atgoing to MongoDB, I will take a look at that again

**Comment by misakitchi** [comment]
Good idea for multi-threaded DB.

To finish on ban thing: AniDB have disable API v1, its why i have 504 ban, right?
And only your old server, who cost you money, had API v1 OK. But you shutdown it...
