### ISSUE TITLE
SQLite lots of disk acces (I/O)

### ISSUE THREAD

**Issue by misakitchi** [japanesemediamanager/jmmserver#135]
With SQLite there are lots of disk acces :(
Is there a way to have less? (use cache or something like that?)

**Comment by jmediamanager** [comment]
The best way to use less is to use mysql/sql server
SQLite is useless

**Comment by jmediamanager** [comment]
My last comment was a bit abrupt :)

I am looking to phase out SQLite support at some stage, so best not to use it.
I see that MySQL has some support to migrate from a SQLite database as well, but I haven't tried it yet.

SQLIte is not meant for multi threaded applocations

**Comment by misakitchi** [comment]
I give up on SQLite very too slow :(
