### ISSUE TITLE
Smarter Scheduled Updates (Files and Series Info)

### ISSUE THREAD

**Issue by misakitchi** [japanesemediamanager/jmmserver#136]
I have one question and one request

Question: when JMM server start are the thing in "scheduled updates" doing once even if i set to "never"?
Example if i put "Auto update files with missing info" to "Never": when i start JMMS will the "files with missing info" be update once or not?

Request: in the scheduled updates can we have: Never, Only once (at start), 6H, 12H, 24H, 48H, 72H, Week, 2weeks, 3weeks, Month, 2months

Same question/request about "Community Sites" i want to updates info/images of TrakTV and TvDB only every week or month not 24h!!!

An another method will be to define when the updates can be done
For example i don't use my PC from 9h-14h, so updates can be done at this time...

Thanks! :)

PS: and why i m asking this, i explain:
My PC is very old and slow... and i reinstall JMM with SQLite who is VERY slow! :(
I shutdown my PC when i go sleep (night), so when i put it ON (morning), the updates for all JMM things (AniDB update, TrakTV, TvDB...) take at least 3-4h!!!!
So every day its very annoying! Because when updates my CPU is about at 60% average and lots of disk access... yes my PC very old... :(

**Comment by AreFinstad** [comment]
i do agree with updates should be further apart as my JMM server can barely finish one 24 update process before starting the next one (well it can but not when i need an VPN to access the AniDB API like i do ATM)

you could have two ways up file updates IMO, one for new files like this: if there is a new file released/added to your server then it will update that series every 24h or so. but if it has not had a new file for say a week-month or longer it will only do it once. (as metadata would most likely be final at that point)

this way it would try to update WAY less files, making the hole update process shorter and it would not waste time on things it really didnt need to update anymore.

**Comment by misakitchi** [comment]
Yep very good idea! :)

And i forgot to ask how often are the "Unrecognized Files" updates? Once each start, 24h, never... ?

**Comment by misakitchi** [comment]
And i understand what is "Auto Sync MyList info".
But what is "Auto get MyList Stats from AniBD"? Its not the same thing?

**Comment by misakitchi** [comment]
Hello!
Is there any news for a Smarter files(unrecognized)/"series info" updates?
Thanks!

PS: to continue idea from AreFin: for "series info" update
for series of current anime season (example: Spring 2015): update "series info" every 24h
and for series older: only update every week/month

**Comment by misakitchi** [comment]
Sorry, but i don't see any change in the option to update series...
Can you explain what did you change?

Say me if i m not correct, but for me:
"Auto. Update Anime and Episode Information" (JMM Desktop/Settings/AniDB) == "Update All AniDB Series Info" (Button in JMM Server)
So if i put "Auto. Update Anime and Episode Information" (JMM Desktop/Settings/AniDB) = 24h, normaly the whole series must be updated every 24h?! (I have 1455 files/series in my \JMMServer\Anime_HTTP folder)

When i ask for a "Smarter Update" of series, i was thinking for exemple at:
-Anime older than (AA) months: update every (BB) hour/days/weeks/months
-Anime newer then (AA) months: update every (CC) hour/days/weeks/months
With for example AA=4, BB=1 month and CC=1 week

Thanks for your hard work! :)

**Comment by jmediamanager** [comment]
No, it doesn't update all information if you are just selecting the scheduled update.

Both AniDB and TvDB will give a list of series that have been updated since the last time JMM Server checked, only these are updated (so it is quite safe)

**Comment by misakitchi** [comment]
OK!
But can you add 1week and 1month to the 6h/12h/24h?
I think some people will use it...

Or can you add the alternative system (Smarter Update) i ask you?
Because i m pretty sure that "AniDB and TvDB will give a list of series that have been updated since the last time JMM Server checked" is not working properly... (i can see that there was change on a serie, but its not updated...)

thx!
