### ISSUE TITLE
Share Images setting during install

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/jmmserver#14]
**Reported by aznkvaj, Jun 4, 2012**

Please include an option when JMM desktop and server are installed at the same time to share one image folder.

**Comment by ElementalCrisis** [comment]
I believe @maxpiva is looking into this.

**Comment by da3dsoul** [comment]
I believe this is done @ElementalCrisis

**Comment by ElementalCrisis** [comment]
Yep, added in 3.7
