### ISSUE TITLE
support Mapped Network folders

### ISSUE THREAD

**Issue by AreFinstad** [japanesemediamanager/jmmserver#140]
support Mapped Network folders.

you should support mapped folders (mounted) like Nas drives and so on.
if a user have mapped a network drive to a drive letter in its OS then we should be able to use that folder structure aswell.

say if i have a Nas drive tied to the drive letter Z in my OS, i should be able to use paths with Z in them.
ATM we cant, JMM does not even know about my Nas drive at all it seems.

it sees my Nas drive if i go to the network or input the link starting with \\ 

at the JMM Desktop you have some Import Folders settings where you manually set the Local Path of the folder, this does not work for me at all (when i open folders from JMM of an episode it will throw me to the Network Location and not the Local path)

![](http://puu.sh/gJBC6/4a59a04585.png)

as its set now my Nas Drive is \\NSA325-v2 and that is mapped to the Letter Z Locally, JMM does not know or care about the Z path at all eventho its in my Computer and many other programs use it flawlessly. 

just find it annoying that the local path isnt used as if i have another folder open with the local path it will copy instead of moving files over (since its not the same drive path anymore) (this copies and deletes, so i takes up space) in any case, it would be better if the path substitution worked as expected (like how MediaBrowser does) 

![](http://puu.sh/gJBUA/19ea8fdfb1.png)

**Comment by Animeimp** [comment]
How is your NAS presenting the shared folders?  I am using the Synology NAS device, drive Z just as yours, and JMM has no problem with it having the drop folder, and stored folders to that path.  The JMMDesktop plays any requested video with no issues.

Which NAS are you using?

**Comment by AreFinstad** [comment]
play videos isnt the issue here at all, its getting JMM to open the folder locations of the files in the local path over the shared path.
at this point JMM will clearly see files in the shared path but it will not understand it if the local path is set to Z over \\NASDrive or whatever. 
we have a system like in EMBY but it does not work correctly as it will only accept the remote path over the local path no matter what. i can type in Z:\Anime into windows explorer and it will find my anime folder fine, but if i do set the local path to Z:\Anime in the JMM Local path setting then it will not work. the remote path should be whats its shared on the network and the local path would be whats for the local machine you are using.

mostly the issue is that when ever you open up a folder location it opens the remote path since it doesnt know about the local one, and if you where working with local paths already in explorer or whatever then it would handle files differently (like moving instead of copying and so on)

**Comment by trillex** [comment]
I have this issue as well, but it only came after upgrading to Windows 10 from Windows 7. 

Funny thing is that it have worked just fine, until I accidentally pressed "Remove Missing Files". Then JMM became aware that, hey, it can't really access these files and marked them all missing. 

When trying to save the import folder, it tells me: "Cannot find Import Folder location" and it cannot be fixed by using JMM Desktop, as written by AreFinstad.

**Comment by trillex** [comment]
Sorry to poke on this matter, but is there a workaround? Watching anime have pretty much gone to a standstill as I rely on this + PLEX to watch.

Thanks for your awesome continued work. :)

**Comment by ElementalCrisis** [comment]
Maybe this will help. 
http://jmediamanager.org/faq/#unable-to-access-shared-drive

**Comment by trillex** [comment]
Sadly not working for me, but thanks. :)

**Comment by ElementalCrisis** [comment]
You might be able to get additional help on our Discord server. 
https://discord.gg/0XKJW7TObKIX4Ug2

**Comment by Baine** [comment]
which win10 version do you use?
i'm on win10 pro, and there i've got it working multiple times now.

and i second what ElementalCrisis said, we'll be able to help you better through discord :)

**Comment by trillex** [comment]
Hi, thanks for the support. :) I'll jump on Discord when I have a bit of time to look more into it.

I'm using Windows 10 Home, which could be the culprit.
