### ISSUE TITLE
Crossovers might force anime got stored on the wrong directory.

### ISSUE THREAD

**Issue by maxpiva** [japanesemediamanager/jmmserver#142]
Some ANIDB episodes (Crossovers, Toriko x One Piece, etc) are in both Series, because the way JMM   get the default directory. (If there is an episode already stored, then use the episode path).

Per example:  If Toriko gets populated before one piece, and you got the crossover, One Piece episodes will end in the Toriko directory... and viceversa. Related to #38

**Comment by AreFinstad** [comment]
this issue has been around for years now. i for one don't watch Toriko but i do watch One Piece..... in the end JMM made a Toriko folder and placed the 2-3 crossovers in that folder eventho i didnt have any episodes of the series before that.

you could have a priority system in place for the placment of the file. say if you have more episodes of the one series of the crossover than the other then it will be placed in the folder with a higher episode count.

in JMM and all the programs using the JMM server in the other hand it should ofc show up on all series its a part of (not sure of it does this ATM.....)

**Comment by jmediamanager** [comment]
Basically I need to change the way JMM determines which folder files get moved to.
I also see an issue where the Drop folder gets set as the default folder for new series every now and then.

The reason for this bug is that it currently determines the folder for a series by looking where the latest episode is. I will add an exception to not use these type of episodes in the determination 

This issue will add the ability to select a series and set it as the default folder for new files, and also view all the folders where files are stored.

**Comment by anzerman** [comment]
would be nice when browsing collection via the JMMdesktop application to have the path to file shown after you expand the episode information :) 

Maybe even highlight it as green (the words that make up the path i mean) if it is in the correct directory and red if it is not in the correct show directory.

**Comment by jmediamanager** [comment]
just a note - you can already see the full path of the pile when you hover over the file name

**Comment by maxpiva** [comment]
Guidance:
AniDB_File has AnimeID but is used as Master Series, the real relationship is one to many, One AniDB_File could belong to more than one series.

ANiDB_File contains a list of episodes, those episodes could contain more than one series.

A Physical File should be stored, in the master series.

this checks should be added:
Create or update additional series, if the list episodes, contains an aditional animeid.

Possible solution:
Maybe adding AnimeID has additional parameter to CommandRequest_GetEpisode.
If the episode AnimeID is different to the one passed on the parameter.
Create and/or Update additional series.
