### ISSUE TITLE
Latest update causing poster and summary problems in MyAnime 3.4.2.16

### ISSUE THREAD

**Issue by xsystematic** [japanesemediamanager/jmmserver#144]
Just updated both JMM Server and desktop and now MyAnime 3 fails to load posters or summary, as seen below. (Second picture shows black lagoon poster) After first loading MyAnime3, which ever poster it shows first is the one that will remain. However if you have several series in a single group, opening that group will display the posters and summary in the group properly.
![untitled](https://cloud.githubusercontent.com/assets/10373766/7456983/c39ecc22-f280-11e4-9ae4-d364e2276ea6.png)
![untitled1](https://cloud.githubusercontent.com/assets/10373766/7457079/b5bebe36-f281-11e4-8f72-14ac1f65d798.png)

Not tried with the latest MyAnime3 yet as I can't find a download link. Downgrading JMM Server fixes the issue. I'm using Media Portal 1.11.0

**Comment by maxpiva** [comment]
I think my anime do not support titan skin. I have a branch of Myanime 3
that supports titan skin, but is a work in progress, since some changes to
the my anime plugin make it not compatible with other skins. In short the
other skins should be changed to support it.

**Comment by xsystematic** [comment]
MyAnime 3 works fine with the titan skin and I just tried the StreamedMP skin with no problems using JMM Server 3.4.2.1.9  but after upgrading to JMM Server 3.4.3.1  I get the problems mentioned above with both skins. For now I will stick with JMM Server 3.4.2.1.9

**Comment by jmediamanager** [comment]
Hi, please download the latest version of MA3 at
http://www.team-mediaportal.com/extensions/movies-videos/my-anime-3

You will need to stats with JMM 3.4.3.x, to avoid issues with changes to the AniDB API

**Comment by xsystematic** [comment]
Working fine now, thanks

**Comment by jmediamanager** [comment]
Thanks for the confirmation
