### ISSUE TITLE
Bug. Latest update breaks Custom Group Filters.

### ISSUE THREAD

**Issue by Darken5** [japanesemediamanager/jmmserver#146]
Any time i click on one of my custom Group Filters (made from New Group Filter) I get an error message saying "object reference not set to an instance of an object". and when i try to make a new group filter i get a wall of text when i click "New" under Filter Conditions.

"The message with Action 'http://tempuri.org/IJMMServer/GetAllTagNames' cannot be processed at the receiver, due to a ContractFilter mismatch at the EndpointDispatcher. This may be because of either a contract mismatch (mismatched Actions between sender and receiver) or a binding/security mismatch between the sender and the receiver. Check that sender and receiver have the same contract and the same binding (including security requirements, e.g. Message, Transport, None)"

**Comment by jmediamanager** [comment]
What version is your JMM Server and Desktop?

**Comment by Darken5** [comment]
Server 3.4.3.2, Desktop 3.4.3.1

**Comment by jmediamanager** [comment]
Which database are you using?
And if possible could you upload your server logs somewhere

**Comment by Darken5** [comment]
ok, this is weird. i went ahead and downgraded both to:
 JMM Server v3.4.2.19
JMM Desktop v3.4.2.18
then updated again to latest. aaaand everything works.... ugh, must of had a bad update.

**Comment by jmediamanager** [comment]
Yeah the issue you are having is usually when the desktop version does not match the server version.
One of the files must have not updated properly
