### ISSUE TITLE
Scraper For Kodi

### ISSUE THREAD

**Issue by scj643** [japanesemediamanager/jmmserver#149]
I have found that this works great for organizing my anime. The downside is that I use Kodi as my media center and all the scrapers fail to organize my anime. A scraper that would work with Kodi would be nice or a plugin.

**Comment by jmediamanager** [comment]
This is already covered by issues #7 and #8

Although it is still called XBMC
Hopefully not too far away

**Comment by AreFinstad** [comment]
I would still vote for a change in folder management that follows thetvdb standard. This with added tvdb seasons in the renaming scripts would support more than just kodi/xbmc.
This way you don't really need to make an app or pluggin to support just one server.
It would be more universal.
Just my two cents though

**Comment by scj643** [comment]
The reason why I asked is because kodi requires it's content in a very specific format and while seeding torrents that format can not be met.
