### ISSUE TITLE
Add "Has Trakt Link" group filter.

### ISSUE THREAD

**Issue by CatmanIX** [japanesemediamanager/jmmserver#153]
To go along with our "Has TVDB Link", "Has MAL Link", etc. filters.

**Comment by CatmanIX** [comment]
Should this have been put here or on JMMDesktop's issues page?

I don't know which one is responsible for group filters or whether it even matters.

**Comment by jmediamanager** [comment]
It is cahnges to both, so here is fine

**Comment by jmediamanager** [comment]
I am closing this issue.
I have decided to do this differently by creating a new utility where you can bulk manage all these types of links, which should make it much easier to do linking, fix broken links etc,
