### ISSUE TITLE
Help Compiling JMMServer with Visual Studio 2013

### ISSUE THREAD

**Issue by misakitchi** [japanesemediamanager/jmmserver#154]
I still have the 100% CPU Bug with JMMServer
So i was thinking to compile my own binary, perhaps it will don't bug...

So i install Visual Studio 2013
To take the code of JMMServer i install GitHub and do a "Clone to Desktop"
The Source code is sync cool :)

After that i open "JMMServer.sln" in VS2013 (its in the GitHub folder and jmmserver)
I choose "release" and generate the 4 projects: miracle no error!
The compilation is good, the only file who don't generate is mediainfo.dll...

Then i launch jmmserver and... it's version 3.4.1.0... :(

So my question: is the source code on github up to date or i have done a mistake?
And where can i find the lastest source code?!
Thanks! :)

**Comment by jmediamanager** [comment]
Yeah sounds like something is not quite right to me.
The source code should be pretty much there, except for the stuff I am working on now

Take a look at the Project Properties and assembly version

**Comment by misakitchi** [comment]
The assembly version say v3.4.3.1 but when generate in VS2013 and launch, i have still "504 Client Banned"... :(
And i have no x86 or x64 folder with hasher.dll, MediaInfo.dll and SQLite.Interop.dll, those files are still in root folder of jmmserver
PS: mediainfo.dll is not generated... :(

Another question: is it possible to do a "Stand Alone" executable? So no need to install .NET

**Comment by jmediamanager** [comment]
MediaInfo is an external library, I package it as part of the installer.
Same with everything in the x86 and x64 folders

No it is .NET only sorry

**Comment by misakitchi** [comment]
OK so i delete jmmserver from github, delete all files and download it again.
Note: there must be a problem of sync in GitHub software...

After that i generate the project: now i have jmmserver v3.4.3.2 with folder x86 and x64

I launch it and... i still have the CPU bug... :(

I see that in properties of the project that we can choose version of .Net, i will try to change.
Is there another thing that i can try?

**Comment by Animeimp** [comment]
https://www.jetbrains.com/profiler/

Try this perhaps to identify which area is causing the 100% bug.  

Also, what antivirus software, or firewall software are you using?

**Comment by jmediamanager** [comment]
You can't really change the version of .NET
Checking your anti-virus is probably a good idea

**Comment by bigretromike** [comment]
Aint this resolve. You cannot compile Hasher (which is part of JMM) with Build Tool other than v140 which is part of Visual Studio 2015
