### ISSUE TITLE
initializing stats takes over a minute when starting jmmserver

### ISSUE THREAD

**Issue by xsystematic** [japanesemediamanager/jmmserver#159]
When first loading JMMServer it cycles through its operations till it gets to initializing stats then I have to wait over a minute for it to complete. From my log file this one takes the longest.
=> StatsCache.InitStats GetAllGroups (Contracts) in 62134.8 ms

Todays log file is here
http://s000.tinyupload.com/?file_id=00240151331242114394

Thanks

**Comment by AreFinstad** [comment]
this is far from uncommon, mine takes about 3min and 50sec.
the more series and groups you have the slower the start will be, aswell as how many tasks you have on startup.
its an media server, it suppose to be running in the background at all time and not just opened when you use it. 
1-5min startup doesnt hurt it TBH as its an server. if it was JMM desktop in the other hand i would stress it for a speedup.

**Comment by maxpiva** [comment]
StatCache Initialization was already slow, and on the top i make it slower caching Plex metadata, currently I cannot find a better solution right now without changing the way JMMServer works or loosing Plex speed.

**Comment by xsystematic** [comment]
ok thanks for the replies

**Comment by jmediamanager** [comment]
Hi @xsystematic, one last question.
Roughly how many series do you have?

Other things that will affect start up speed is the number of group filters you have.
And also the number of users you have -> You can delete any users you don't plan on using.

**Comment by xsystematic** [comment]
Around 170 or so. I have managed to get it down to about 16 seconds on initializing stats. I did this by changing my processors overclock settings to optimized (from disabled) and changing a few other BIOS settings.
