### ISSUE TITLE
JMM Server Log Full Of Errors

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/jmmserver#160]
Hello,

I just recently re-installed JMM Server after upgrading to Windows 10 and noticed that after running for 24 hours, I still had a pretty big hasher and general que list. I took a look into the log file and noticed it's filed with quite a few errors.

In addition I'm also experiencing a large numbers of series not having a tvdb link in JMM Desktop, I can manually add it but it seems to not automatically create the link. I don't know if this problem is related to my first problem but they started happening around the same time. 

Here are my logs.
https://mega.co.nz/#!rdIkkLrD!rSrMmrS_A8XwIvEBYEbA4V3wU12tk5zZkAPJ-ADbeF4

**Comment by jmediamanager** [comment]
Those errors are related to connecting to AniDB.
The hasher list should be reducing regardless though.

Has anything firewall related been turn on after the upgrade?

**Comment by ElementalCrisis** [comment]
I redid all my settings, removed and re-added both JMM Server and Dektop from Windows firewall and reinstalled JMM. Seems to have fixed the problem and now hashing correctly. 

I think this error is the reason I'm having problem with shows not linking with TvDB. 
Error|CommandRequest_TvDBSearchAnime.ProcessCommand => TvDBHelper.SearchSeries => TvDBHelper.Init Error in TVDBHelper.Init: System.Xml.XmlException: Root element is missing. There's 646 instances of it in my logs.

**Comment by jmediamanager** [comment]
That just means it tried to gte data from TvDB, which probably failed, so that error then occurred

**Comment by ElementalCrisis** [comment]
Gotcha, any idea on why I keep getting these errors? I don't mind having to manually link TvDB but as it stands I have to do it for around 60+ series.
