### ISSUE TITLE
[BUG] Ignored Files

### ISSUE THREAD

**Issue by misakitchi** [japanesemediamanager/jmmserver#162]
When i move a folder were there are "ignored files", then the ignored files go in "Unrecognized files"...
So i must say that its "ignored files" again...
Its very annoying... because i move lots of files/folders...

**Comment by RickDB** [comment]
Added this feature and when you run import and file hash is the same it will mark the file as ignored again even if not in the original location.

So even if you rename the file it will still match this way, kept the method light but does add some extra time to the import process depending on size of collection.
