### ISSUE TITLE
JMMServer 3.4.3.2 not ignoring non-media files

### ISSUE THREAD

**Issue by Animeimp** [japanesemediamanager/jmmserver#163]
I have many series that have .sub/.srt/.ass subtitle files, but each time JMMServer runs an import, it is constantly trying to import/look up those files.  Is there a way to tell JMMServer to ignore all those files?  It has reached a point where the server is no longer importing new media files in the \unprocessed folder because it gets tied up with all the non-media files in the \sorted folders, and then seems to forget where it was at.

**Comment by AreFinstad** [comment]
by default the JMM server does not Hash those external sub files unless you add those file types to the settings tab in JMM Desktop under Settings>Essential>Import Settings.
remove the file extension from that setting and it should stop it from importing those file types (just double checked here myself)

only other way you can fix this is by adding them to the ignored list in the Utilities tab.

also by removing the files in question also fixes this issue (like searching for them with either Windows Search or Search Everything (much better IMO)) and then moving them out of the scan folder (or deleting them depending on if you need them at all ( you did call the non-media files after all.....))


if you already knew all this and want to cheeky response, just don't. I'm just trying to figure you out and help you here.

**Comment by Animeimp** [comment]
*nods* Just the default value is in there "MKV,AVI,MP4,MOV,OGM,WMV,MPG,MPEG", I have never messed with that.  But noticed when some media files had not been imported after four days, and checked the log file:
[2015-08-17 18:07:23:660] Info|BackgroundWorker.WorkerThreadStart => MainWindow.workerImport_DoWork => Importer.RunImport_NewFiles Processing File 1/18447 --- \\DISKSTATION\Storage\Anime\Sorted\error.log
[2015-08-17 18:07:23:660] Info|BackgroundWorker.WorkerThreadStart => MainWindow.workerImport_DoWork => Importer.RunImport_NewFiles Processing File 2/18447 --- \\DISKSTATION\Storage\Anime\Sorted\Hoshi no Umi no Amuri\Hoshi no Umi no Amuri - 1 - The Blooming Flower Likes The Night Sky [ujisub](9d8fe42d).ass
[2015-08-17 18:07:23:660] Info|BackgroundWorker.WorkerThreadStart => MainWindow.workerImport_DoWork => Importer.RunImport_NewFiles Processing File 3/18447 --- \\DISKSTATION\Storage\Anime\Sorted\Rayca\Rayca [raw](ec7104b3).ssa

That it was going through \Sorted folder, looking at the non-media files.  The scan folder is \unprocessed, and JMM renames the media files, placing them in the \Sorted folder.

They are needed, because they are the subtitles for those media files that don't have the subtitles hard set, or in a .mkv package.

**Comment by jmediamanager** [comment]
Ok that is strange.
What is supposed to happen is that when it moves a Video file, it also looks for sub-title files to move as well.

But It is not supposed to hash them.

**Comment by Animeimp** [comment]
What is even stranger is that these subtitle files have been in the series \Sorted folder for months.  I've always kept the subtitles seperate, and manually move them into the series \Sorted folder after JMM has finished importing them.  They have never been in the \Unprocessed folder at all.

**Comment by AreFinstad** [comment]
well i have added an issue like this a few years back with sub files and other external files to follow the main file. 
has never worked as expected for me, the sub files have always stayed behind even when i add the file types to the settings. 

is these subs tied to the name? some have different file names over the main video file. some have a .eng and the end and so on.

**Comment by Animeimp** [comment]
After JMM imports/renames/moves to \Sorted the media files, I match the spelling of the subtitles to the media files, and move them into the \Sorted folder manually.  The subtitle files are never placed in the \unprocessed folder at all.

**Comment by AreFinstad** [comment]
ahh i see, well the amount i download at every day i just couldn't be bothered doing it that way.
its still an issue, but no the same issue im thinking about XD

**Comment by hidden4003** [comment]
I've checked the code and it seems that log message is confusing, it doesn't mean that file will be hashed, just shows that file was considered for processing.

**Comment by ElementalCrisis** [comment]
After talking with @hidden4003 and running some tests I don't think this is an actual bug but a slight misunderstanding on how this process works. JMM will move the episode and the .ass file if they have the same name and the .ass file is present when hashing the file. However, it will not move .ass files if the file they are associated with has either already been hashed or named differently. But it will move an .ass file that has been sitting in the Drop Source if it hashes the associated file that was added after regardless of how long the .ass file has been in there.

The message in the log file will be changed to be more clear so there isin't any misunderstandings in the future.
