### ISSUE TITLE
UI Freeze on Cancel

### ISSUE THREAD

**Issue by Rand-Random** [japanesemediamanager/jmmserver#165]
I tried to cancel Image Downloads because the number increased to 12.000 but the UI froze.

After looking at the Code I believe the problem is of more general nature and can happen with all cancel operations inside JMM Server.

Have a look at this method:

void btnImagesClear_Click(object sender, RoutedEventArgs e)
{
	try
	{
		this.Cursor = Cursors.Wait;
		JMMService.CmdProcessorImages.Stop();

		// wait until the queue stops
		while (JMMService.CmdProcessorImages.ProcessingCommands)
		{
			Thread.Sleep(200);
		}
		Thread.Sleep(200);

		CommandRequestRepository repCR = new CommandRequestRepository();
		foreach (CommandRequest cr in repCR.GetAllCommandRequestImages())
			repCR.Delete(cr.CommandRequestID);

		JMMService.CmdProcessorImages.Init();
	}
	catch (Exception ex)
	{
		Utils.ShowErrorMessage(ex.Message);
	}
	this.Cursor = Cursors.Arrow;
}

The problem is within "wait until the queue stops" routine, because it can happen that between the Stop() and the next Iteration of the while Loop the workercommand again gets started from its cancel state.

In my case the JMMService.CmdProcessorImages.NotifyOfNewCommand(); method inside CommandRequestImplementation gets kicked off again, and so the bool ProcessingCommands again gets true.

To fix the problem I think there are 2 solutions:
1.) while loop a boolean that says true to the workercommand that actually got canceled, no matter if a "new" workercommand starts
2.) try to not only cancel the current workercommand but also the routine that is in the middle off notifing new commands

I think the 2nd one is the better one, since with the first one the user would have to hit the cancel button again and again if the software is in the middle of adding commands to the queue.

**Comment by Rand-Random** [comment]
Another approach could be to redesign the start of JMM Server so that it starts it work AFTER it queued up all commands so that you can cancel them only after they are initialized.

**Comment by Rand-Random** [comment]
Just love the close and comment button. :)

**Comment by ElementalCrisis** [comment]
I would say submit the commit with the change you think would work best. I'm sure lwerndly wouldn't mind as the whole reason JMM was moved to GitHub was to allow others to help out.

**Comment by AreFinstad** [comment]
agreed, if you have the skills and know-how then just do it, our creator and savior will review it and if its good then its great :P

**Comment by misakitchi** [comment]
Good to have people with programmation skill :)

**Comment by AreFinstad** [comment]
can't agree more, after following this project for years now and have made hundreds of issues on here and the code.google site i do really miss out actually helping out on things, i dont even know where to start TBH XD

**Comment by ElementalCrisis** [comment]
Download Visual Studio Express for Desktop (https://go.microsoft.com/fwlink/?LinkId=615464&clcid=0x409) and start messing around with JMM Desktop and JMM Server. I'm on my phone so I don't have the links but Google C# tutorials, WPF tutorials and Visual Studio tutorials. For me the vide tutorials work best as you can follow along.

**Comment by jmediamanager** [comment]
There are a couple of things I will probably look at.

1 - Change the image queue to an in-memory queue instead of a database queue, it is not important if these commands get lost because it does a reconciliation every time JMM server starts
2 - Instead of iterating through the database and deleting one by one, issue a single sql delete statement.

**Comment by DimT** [comment]
After my Internet disconnected hasher stopped working and can't cancel the queue.
Are there any suggestions?

**Comment by bigretromike** [comment]
restart server?

**Comment by DimT** [comment]
I have already tried restarting, pausing and resuming each queue and all together and starting another job. Nothing worked.

**Comment by bigretromike** [comment]
Is queue full ? or empty ? can you force hash some small folder in the folder list?

**Comment by DimT** [comment]
There are 1443 items in queue but appears idle.
Could you explain how I can force hash?

**Comment by bigretromike** [comment]
in Server, on "import folder" tab, click on "Scan", yellow icon on left of folder name. Make new folder, copy 1-2 files there. add that folder. It should add it to queue automaticly.

Also maybe you have really big file that is taking so long to scan ?

**Comment by DimT** [comment]
Thank you!
I changed the import folder to a new one with 2 files and the queue went down.
Then I changed back to the old folder and everything seems fine.
The file was ~300MB and hasher was stuck for over 12 hours.

**Comment by ElementalCrisis** [comment]
Hopefully we can get the solution @rand-random mentioned implemented.

**Comment by hidden4003** [comment]
I've fixed it in a  way that now it waits until the running command is finished and then removes everything. Feel free to reopen if you feel fix is incomplete.
