### ISSUE TITLE
JMMServer install file has 9 malware/virus listed in it.

### ISSUE THREAD

**Issue by Animeimp** [japanesemediamanager/jmmserver#166]
My system crashed, so working on rebuilding.  Downloaded the JMM_Server_Setup_3.4.3.2.exe.zip file from http://japanesemediamanager.github.io/downloads.html - Firefox did not want to go to page, nor download the file.  Used https://www.metascan-online.com to scan the exe file, and 9 of the antivirus scanners found problems.

Antiy  Sep 08 2015 (More than 15 hours ago)  Trojan/Win32.Sefnit
Filseclab  Sep 07 2015 (More than 2 days ago) W32.InstallCore.XB.hwzw.mg
Fortinet  Sep 08 2015 (More than 15 hours ago)  W32/Sefnit.XMD!tr
Ikarus  Sep 08 2015 (More than 15 hours ago)  Trojan.Win32.Sefnit
Lavasoft  Sep 08 2015 (More than 15 hours ago)  Trojan.GenericKD.2643644
McAfee-Gateway  Sep 08 2015 (More than 15 hours ago)  BehavesLike.Win32.Trojan.rc
QuickHeal  Sep 07 2015 (More than 2 days ago)  Trojan.Sefnit.g8
Symantec  Sep 07 2015 (More than 2 days ago)  Trojan.Gen
ThreatTrack  Sep 08 2015 (More than 15 hours ago)  Trojan.Win32.Generic!BT

**Comment by maxpiva** [comment]
I doubt any malware is in it, most likely, the installer used, is also used by malware creators.

**Comment by AreFinstad** [comment]
to be fair, the site has have loads of issues like this the last two weeks for some reason, it has never flagged for google or antiviruses before this so i really think its weird. 

both the site and JMMD is safe it seems:
https://www.virustotal.com/en/url/517e24606272e965b82a0b52aef76f4daec86a34a91d65171072bf7e718007a9/analysis/1441815306/
https://www.virustotal.com/en/file/1ffbc35d507f5a84fcf66e31165ff7b8e9fef31c65d3cfdadd618728ee01000f/analysis/1441815362/

but the JMMS on the other hand does not look that good:
https://www.virustotal.com/en/file/d37cba6f22898017774038970f1d3876a5b77c0a8e2687b650871286cf13c831/analysis/1441815334/

doesnt help either that chrome and FF does flag us with a warning when we enter the site, IDK anymore, it all just seems weird to me :/

**Comment by Animeimp** [comment]
The installer would not trigger so many warnings.  Sadly, it is very possible the site has been comprised and someone has managed to add malware to the install file.  Maxpiva, do you have admin rights on the site?  Can you rebuild the install file, and compare CRC's with the one on the site?

**Comment by AreFinstad** [comment]
well anyone can access the files that the site is made of here: https://github.com/japanesemediamanager/japanesemediamanager.github.io

unless im completely wrong everything that is changed there will be changed on the site.... tho im not 100% sure how they handle that.

i noticed issues after this change here tho: https://github.com/japanesemediamanager/japanesemediamanager.github.io/pull/7

**Comment by ElementalCrisis** [comment]
I'm not 100% but I remember reading somewhere that the hasher was what was being flagged.

**Comment by AreFinstad** [comment]
yeah, thats on issue https://github.com/japanesemediamanager/japanesemediamanager.github.io/pull/7

havent tested the file that is live on the site myself (for fear TBH) but the files i have on my install ATM where clean:
https://www.virustotal.com/en/file/7266079f97145c79f801525d5adb440c9c226bede63b570fb51e05bcc906f040/analysis/1441830836/
https://www.virustotal.com/en/file/c13ca5f80f9cb40513b7398ac56b4625c8415dee6155f13625310cdc16b94af8/analysis/1441830735/

**Comment by jmediamanager** [comment]
@ElementalCrisis it might be this change

`
<p>It's extremely easy to start contributing to JMM. Simply register for a <a href="https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0CB8QFjAAahUKEwi2iPzNz8zHAhUGXJIKHQ-ICzk&url=https%3A%2F%2Fgithub.com%2Fjoin&ei=P8XgVfbsCYa4yQSPkK7IAw&usg=AFQjCNF6nezHQWX1hKwEFQVYRrUheS9_Ig" target="new">
`

Here's what Google webmaster tool says:

Open redirects are coded with the intention for the URL structure to allow the addition of another URL so users can reach a useful file or webpage on the site. For example:

`http://example.com/page.php?url=http://example.com/good-file.pdf`
Hackers can abuse open redirects by adding their spammy or malware page to the site’s open redirect, similar to this:
`http://example.com/page.php?url=<malware-attack-site>`

**Comment by jmediamanager** [comment]
Ok, I'm pretty sure that it is the x86 version of the hasher.dll used in 3.4.3.1

I can confirm all the threat warnings when using local and online virus scanners.
Have done a rebuild of the hasher dll, and it seems to fix the issue.

I will upload it some time today, once I think it looks good (will also be doing the auto updater)

**Comment by AreFinstad** [comment]
will you add the new changes to the beta client while updating the auto updater? pretty plz? >__<

**Comment by jmediamanager** [comment]
The beta will auto update as well.
The official version will be the full source

**Comment by AreFinstad** [comment]
nice, now i can come back to linking again. just too big of a pain with that pop up error every time XD

**Comment by jmediamanager** [comment]
Just doing scans of new builds now.
Should be available within next 30 minutes

**Comment by jmediamanager** [comment]
Everything is updated now.
NOTE - I have request a review from Google again, so the site may still have issues, but the actual fines seem fine to me

**Comment by ElementalCrisis** [comment]
Sorry about that, that must of been when I copied the link directly from Google.

**Comment by ElementalCrisis** [comment]
When I get home I'll fix that link.

**Comment by Animeimp** [comment]
Yes, all of the virus scanners are happy now.  Thank you!

**Comment by Anvirol** [comment]
I've been updating JMM server and JMM desktop pretty often and now my computer seems to be infected by trojans in the hasher.dll..

I thought it would be a false positive and just ignored it, but after Firefox and Chrome started blocking the website I finally realized my mistake..

I'm going to format my computer and I'm just wondering if the current binaries are safe?

**Comment by AreFinstad** [comment]
the new files have been changed and has passed the testes at google aswell as stated above.

**Comment by ElementalCrisis** [comment]
@Anvirol It is a false-positive, nothing to worry about. @jmediamanager rebuilt hasher.dll specifically because of this issue and you'll no longer get the error messages. Just to make sure you're running the latest version as the auto-update has been having problems, download these files.

http://www.jmediamanager.org/jmmdesktop/jmmdesktop.all.to.3.4.4.3.zip 
http://www.jmediamanager.org/jmmserver/jmmserver.all.to.3.4.4.3.zip

You will get the warning message in Firefox and Chrome, don't worry about it. I believe it's because there's still old versions of hasher.dll available to download.

**Comment by jmediamanager** [comment]
Hi, I need to remove the old binaries from my file host, and ask Google to re-evalute it.
I will do that in the next couple of days

But the current latest files are all safe.

**Comment by jmediamanager** [comment]
Have removed the files and requested a review
