### ISSUE TITLE
Create option to only use AniDB Posters

### ISSUE THREAD

**Issue by misakitchi** [japanesemediamanager/jmmserver#169]
I have some strange things with the last version...

1) When i launch JMM Desktop its very slow...
2) Poster of serie is now TvDB... i prefere poster of AniDB: is there an option to change that?

Thx for help :)

**Comment by jmediamanager** [comment]
Yeah there is another issue to address the performance issue with using TvDB images.

The posters are actually random between AniDB and TvDB.
But I am logging this an enhancement to create an option to always use the AniDB poster

NOTE - I have changed the title of this issue.

**Comment by misakitchi** [comment]
OK thx!
But its strange because before 3.4.4.3 posters were only AniDB image...

**Comment by AreFinstad** [comment]
well thats because i asked for it to be random, sorry about that. i like it that way XD (not sure if random images where the original intent tho (prob was))

**Comment by misakitchi** [comment]
The best is to have a option for Posters: AniDB or TvDB or Random
Its because personnaly i prefere AniDB Posters...

**Comment by ElementalCrisis** [comment]
I think there should be two separate settings. The first is image mode with normal and random and then poster type with AniDB only, TvDB only and AniDb and TvDB.

**Comment by jmediamanager** [comment]
Yeah the fact that is only showed only AniDB posters was actually a bug.

I think only one setting is needed though, since you can still individually control which posters are enabled or not.

**Comment by AreFinstad** [comment]
alot more work with only having one option tho IMO, i mean the user have to choose the images manually on all series every time if that is the case, better off with either fixed (to AniDB OR TVDB) and random as a settings. but that is just my opinion tho, atleast for the end-user sake.

**Comment by jmediamanager** [comment]
well the option would be
- Only use AniDB posters

If you had an option
- Only show TvDB posters

Basically it means you want a random TvDB poster.
There is not much difference by including AniDB posters in that as well.

**Comment by AreFinstad** [comment]
well i guess thats true as theTVDB site has the same poster as AniDB and most of the time is higher res aswell..... didnt think of that XD
well sounds fair to me :D

**Comment by misakitchi** [comment]
I don't like random posters because, if the poster of a serie change i don't recognize the serie anymore lol! I have not lots of memory in my head lol! :D

**Comment by AreFinstad** [comment]
meh, there is always text there anyway so i really dont see the issue XD
yeah, i do get that it can be a bit confusing when you are just using images to connect the series in your head. but there is always text and the characters stay the same aswell.

**Comment by jmediamanager** [comment]
Available in next release
