### ISSUE TITLE
[Feature] Internal Chat/IRC

### ISSUE THREAD

**Issue by misakitchi** [japanesemediamanager/jmmserver#170]
I would like a Internal Chat or IRC to speak with JMM users XD
OR Messages BY series...
Because i don't want to speak with TrakTV or AniDB people...

EDIT: we have created a official Chat here:
https://discord.gg/0XKJW7TObKIo51WA
You can come all! :)

**Comment by ElementalCrisis** [comment]
Well there is an IRC channel, irc://irc.rizon.net/jmm but it's kinda dead. We could probably use a forum just for members to talk.

**Comment by AreFinstad** [comment]
well we all can make a Discord channel, its meant for gaming but its nice to text chat, voice chat and file sharing at the same time. and its free to set up and can be used with a browser aswell as its own client.

**Comment by AreFinstad** [comment]
update on this: made a simple little server for us, will be starting with making rooms and both text and voice aswell as making admin/mod groups.

here: https://discord.gg/0XKJW7TObKIo51WA

**Comment by ElementalCrisis** [comment]
So far I've liked what DIscord can do. if @jmediamanager is ok with it I'll add a link on the site.

**Comment by jmediamanager** [comment]
I already have a HostGator account where I hist all my downloads
It comes with support for a few forums e.g

http://www.jmediamanager.org/forum/

Pretty old school, but effective.

It also supports a few other forum types like MyBB

Note - another option i use at work is called 'Slack'
https://slack.com/

I think it is pretty damn good as well

**Comment by ElementalCrisis** [comment]
Slack is great, I've never had a need to use it but love the idea behind it. Discord is definitely inspired by it. I'm torn between using something like slack or a forum based system.

**Comment by ElementalCrisis** [comment]
OK so I did a bit of research. Discord is infact inspired by slack but aimed at gamers and the gaming community instead of businesses. From what I've read a lot of communities are switching to Discord from Slack as it offers more features for communities though since I've never used Slack before I don't know what features. @jmediamanager can you look it over and see if it would work better for us since you've used slack before?

**Comment by jmediamanager** [comment]
Yup will do

**Comment by jmediamanager** [comment]
At the moment, I am liking Discord, pretty much the same as Slack

**Comment by jmediamanager** [comment]
Discord is now official

**Comment by AreFinstad** [comment]
@maxpiva could you care to join us on the Discord Server? will make you an Admin right away aswell :D 
we are getting some support issues about the Plex Plugin and such over there, it also would be cool to see you around there from time to time if you have the time :D 
just click this link and make an account: https://discordapp.com/invite/0XKJW7TObKIX4Ug2

they have a client aswell on Desktop aswell as Phones if needed.

**Comment by misakitchi** [comment]
So much change and progress since then! :D
