### ISSUE TITLE
[Feature] AniDB Sheduled Updates

### ISSUE THREAD

**Issue by misakitchi** [japanesemediamanager/jmmserver#173]
Hi!
1) In JMM Desktop, AniDB then Sheduled Updates, can you add 1week and 1month?
2) Can you add a option to force "Update All AniDB Series Info" every XX month/week? (Its the button in JMM Server)
Thx! :)

**Comment by AreFinstad** [comment]
dont you already have an issue about this? https://github.com/japanesemediamanager/jmmserver/issues/136

**Comment by jmediamanager** [comment]
NOTE - the second request above will not be done. This was intentionally left out of scheduled updates because it is very likely to get you banned if you run it too often.

It is only meant to be used if something has gone wildly wrong with your data.

**Comment by misakitchi** [comment]
OK for request 2, but for my first request?!!
1) In JMM Desktop, AniDB then Sheduled Updates, can you add 1week and 1month?

**Comment by jmediamanager** [comment]
See above
All scheduled server updates now support additional options of 1 week and 1 month

**Comment by misakitchi** [comment]
I updated to last version of JMM Desktop and Server but i don't see thoses new options...

Here the update timer i want:
Calendar: 24H
Anime and Episode: 24H
Sync MyList: 1 month
Get MyList Stats: 24H (But i don't know for what it is useful?)
Missing Info: 24H
Unrecognized Files: 1 week

Thanks!

**Comment by ElementalCrisis** [comment]
It's there.
![jmmd - new timer options](https://cloud.githubusercontent.com/assets/9443295/10574213/7d2b30c0-7609-11e5-9be5-b399bc5d2bad.png)
When @jmediamanager says it's been added, he means in the next version.

**Comment by misakitchi** [comment]
Its still in the beta, not out?
But i really want to have 2 differents timers for "Missing Info" and "Unrecognized Files", because its not the sames type of files!

**Comment by jmediamanager** [comment]
No it's not out yet, will be out with the next release
