### ISSUE TITLE
Plex usage 100% 

### ISSUE THREAD

**Issue by Eagle97** [japanesemediamanager/jmmserver#176]
![2015-10-09_02-25-57](https://cloud.githubusercontent.com/assets/1307729/10383276/2edf7ca2-6e2d-11e5-9ace-c62fd18b7152.png) 

Plex uses 90% or more and JMMServer usually at 25% cpu when using the plex channel plugin for JMM the latest versions that are on the github.io page.

**Comment by AreFinstad** [comment]
that is the plex transcoder. plex will auto transcode by default if you your codec isn't supported on the player device. meaning if you say play something on your phone for example it will transcode most of the time. nothing can be done with this unless you re-encode your videos in a codec that is supported by your client.
by default the plex transcoder can be a bit buggy at times, this isn't a JMM Plugin issue as far as i know. if you are not watching anything on plex and the transcoder is under load i would recommend to restart your plex server.

**Comment by AreFinstad** [comment]
also for us to actually see whats going on you should share your logs with us, logs of the plex server aswell as the myanime plugin (the JMM plugin).
also on note, this issue is in the wrong place. it should be here: https://github.com/japanesemediamanager/plexplugin/issues

**Comment by misakitchi** [comment]
Eagle97 you can come on our Discord channel to discuss this :)

**Comment by AreFinstad** [comment]
maybe share the link if you invite him, as he is already on the wrong project on this issue he might not be up-to-date on whats where just yet.
we are chatting here:
https://discord.gg/0XKJW7TObKJiXMIq

thats the support chat (not used just yet, but you can be the first! :D )
plz try to use the right text channels when on discord as we like to keep things neat.

**Comment by Eagle97** [comment]
Alright thanks I be sure to drop in.

**Comment by Eagle97** [comment]
But as I no longer use plex and just stick to jmmdesktop and direct streaming without transcoding. If someone wants to open this issue they can do so.
