### ISSUE TITLE
API support for JMMServer

### ISSUE THREAD

**Issue by nettosama** [japanesemediamanager/jmmserver#18]
A sort of web API for JMMServer, to trigger scans on certain folders/files when called. This helps with network folders that can't be automatically detected for new files. Also to trigger rescan on certain files that weren't added to AniDB when first scanned (mainly new releases).

**Comment by ElementalCrisis** [comment]
Being worked on by @bigretromike,

**Comment by bigretromike** [comment]
@ElementalCrisis tells the true

**Comment by ElementalCrisis** [comment]
Jump on Discord when you get a moment, sent you a message with something I wanted to show you.

**Comment by bigretromike** [comment]
sure thing, when only I will have some free time I will check it out

**Comment by bigretromike** [comment]
The part asked for trigger scanning by api is done. So we could close this as that was the main reason @nettosama and other stuff are added anyway. But this title could be misleading as it ask for "api" but specify function in the message.
Also this should also be done inside web-ui already by @hidden4003
