### ISSUE TITLE
using jmm server via webbrowser

### ISSUE THREAD

**Issue by bigretromike** [japanesemediamanager/jmmserver#180]
Hello,

I installed JMM server, started it using Mysql.
Jmm Desktop work without problem, but PlexPlugin isn't (telling about bad user - im using Default).
I narrow problem to point where I cannot access JMMserver from http://ip:8111/jmmserver not http://127.0.0.1:8111/jmmserver nor /video/jmm they give Error 404 (page not found)

I was looking for documentation for this but I cannot found anything. Server is on Win7 x64 - so its not lookback restriction from win8/8.1.

http://localhost:8111/JMMServerBinary?singleWsdl did work, but Im not sure is it the right path or not.

**Comment by bigretromike** [comment]
From Source I see someone did comment out that /jmmserver, 
Is there any docs for /JmmServerREST ?

**Comment by ElementalCrisis** [comment]
https://github.com/japanesemediamanager/jmmserver-webui

**Comment by bigretromike** [comment]
The initial issue wasn't about jmmwebui, I will close it as it was more of the issue with legacy api than anything else, as the legacy api could be used in browser anyway.
