### ISSUE TITLE
JMMServerPlex and Search command broken?

### ISSUE THREAD

**Issue by bigretromike** [japanesemediamanager/jmmserver#181]
Is it working for someone?
when passing ```http://localhost:8111/JMMServerPlex/Search/1/20/akira``` on browser on machine with jmmserver, i get results
```
<MediaContainer viewGroup="show" title1="Search" title2="Search Results for 'akira'..." viewMode="65592" size="0" identifier="com.plexapp.plugins.myanime" mediaTagVersion="1420942002" allowSync="0" totalSize="1" nocache="1" offset="0"/>
```
Same things with others search - I see that "totalSize" going from 0 to up when there is hit, but i dont see the hit. Should it be included in that xml? or is it on other channel?

**Comment by maxpiva** [comment]
Local Search works (In the anime plugin), Global search is somewhat broken, i was unable to hack the way on global search.

**Comment by bigretromike** [comment]
yea, searching dosn't work because it dont give real results. I see that Client transfer data tru binnary format. I would love to have REST interface that work. 

@maxpiva I will invesigate the AnimePlugin

**Comment by maxpiva** [comment]
Hmm, strange, I should check the PlexRest interface, Seems some bug got
introduced in some version.
Last time I checked, search working inside the anime plugin, but global
don't get invoked .

**Comment by bigretromike** [comment]
I think I found the problem there. The ```ToList()``` is also broken there so sorting is out for now.

**Comment by maxpiva** [comment]
Thanks BigRetroMike :)

**Comment by bigretromike** [comment]
Took me some time :-) but was worth the trouble.
Without those rest/api things working I wont be able to try toi make plugin for kodi/xbmc :-) so the back end need to work :-) hope you merge this later so I can fell like I accomplished something here :+1:

**Comment by maxpiva** [comment]
Cannot merge, only Leo has the power :)
Leo, please merge.

**Comment by AreFinstad** [comment]
@maxpiva you could join us to get in direct contact with alot of us over here: https://discord.gg/0XKJW7TObKIX4Ug2
you could use your browser or your phone or even a desktop client. we also have alot of normal users there and so on.
would be faster to just shout there if you want to get in contact with Leo quickly and ofc others that help with the site :D 

ofc we will make you an Admin right away when you join aswell.

**Comment by bigretromike** [comment]
@jmediamanager hear us! ;-)

**Comment by AreFinstad** [comment]
did shout to him over at Discord so he hear us XD
its the middle of night for him ATM tho, its like 5AM for him ATM in Australia, hahaahhaha

**Comment by bigretromike** [comment]
hehehe, that something :-) 
I saw you @AreFinstad contribute to plex plugin. Could you elaborate what dose the video key does for plex which is output in plex plugin like ```/video/jmm/proxy/687474703a2f2f31302e312e312e3130303a383131312f4a4d4d536572766572506c65782f4765744d657461646174612f312f302f33"/``` Is that some kind of url to the file directly ?

**Comment by jmediamanager** [comment]
@bigretromike thanks for the fix, I have merged it in, and should be doing an official release this week as well.

**Comment by bigretromike** [comment]
Sounds great! Thanks

**Comment by jmediamanager** [comment]
NOTE - this has been released already

**Comment by bigretromike** [comment]
@jmediamanager is it me or server cant start after update and crash?

**Comment by jmediamanager** [comment]
Mine works fine,and a few others on Discord are also running it without any issues

**Comment by bigretromike** [comment]
Maybe when it crashed during update it broken. I will restart/reinstall

**Comment by bigretromike** [comment]
ok, reinstall did help :+1: probably when server started during update it locked some files and updater didnt renew them :-)
Thanks for the update! I will try to work on Kodi plugin from now on

**Comment by jmediamanager** [comment]
ok great :)
