### ISSUE TITLE
Mtvmaze.com as an alt source to thetvdb for images, episode summaries, etc. 

### ISSUE THREAD

**Issue by girigirides** [japanesemediamanager/jmmserver#184]
Hiyo! Would it be possible to add http://www.tvmaze.com/ as an alternate source for episode images, summaries, etc. as opposed to relying mostly on thetvdb? 

I linked the api for you here:

http://www.tvmaze.com/api 

It’s just atm, using (mostly) thetvdb only works if a series isn't locked down on a whim (or the admins are feeling particularly tolerant). Many the anime shows listed aren’t able to get proper love due to this limited community input. 

On the other hand, tvmaze currently supports and (more importantly) welcomes community content. So perhaps Maze could be a supplemental option to other sources? I don’t imagine it could replace thetvdb altogether (not just yet at least) since it’s still gaining ground and content. But some work around maybe for shows with incorrect/locked data?

Thanks much!

**Comment by ElementalCrisis** [comment]
I looked into the site, it could be a nice alternative to TvDB but not at the moment. For one it's missing quite a few shows, I picked ten random series from my collection and they only had two listed. TvDB had a listing for all ten series. Also for one of the series I selected, while it did have an listing, the episode listings were bare only containing the episode name and air date. JMM relies heavily on TvDB for this information and while I think TvMaze would be better in the long run, it's not worth the loss of content. 

However they are a fairly new site and actively update/develop their API, I know a feature Leo has always wanted with TvDB is image uploading but it seems they wont add it. If TvMaze were to add that, it would give them something that would benefit JMM. Also I noticed talk about possibility importing data from TvRage, if so then that would solve my issue about missing series and information.
