### ISSUE TITLE
Cannot add folder on network

### ISSUE THREAD

**Issue by dark5server** [japanesemediamanager/jmmserver#185]
I have most of my collection on NAS. The problem is i cant add folder from network such as...
\\192.168.1.30\NetAxcess\Book 01\AnimaX
or mapped network folder 
T:\Book 01\AnimaX
 it shows error ..
```
could not inset: [JMMServer.Entities.ImportFoIder][SQL: INSERT INTO 
[ImportFoIder] (ImportFoIderType, ImportFoIderLocation, 
ImportFoIderName, IsDropDestination, IsDropSource, IsWatched) 
VALUES (?, ?, ?, ?, ?); select SCOPE_IDENTITY()]
```

**Comment by jmediamanager** [comment]
Can you please provide me your full log, as it will have extra details.

It might be easier to PM me on discord
https://discord.gg/0XKJW7TObKIX4Ug2

**Comment by Baine** [comment]
"it's not a bug, it's a feature"... that's what microsoft thinks ;)

that's not a problem in jmm (well, partially it is), but in how Windows handles network mounts and user sessions
as JMM Server requires admin rights to run as of now, the mounted network shares that you see when you browse for a source folder are those of the Administors Session, not of your normal user Session (even though you might have administrative rights and UAC disabled)

to fix that:

run cmd as administrator, mount the share inside that cmd (note: the title of that cmd window should say Administrator: C:\Windows\System32\cmd.exe, or where ever your windows installation resides)
type "net use <x>: \\<server>\<share> /persistent:yes /user:<username> <password>"
replacing the words inside <> with appropriate values and hit enter
after that, you should be able to access that mount with jmm server :)

good luck with that, and if you should need help with that, hit me on discord

**Comment by misakitchi** [comment]
https://technet.microsoft.com/en-us/library/bb490717.aspx

Example:
net use e: \\Server\Anime /persistent:yes /user: 

Not sure if "/user: " is ok...

**Comment by Baine** [comment]
well, the /user parameter depends on how the share is secured...
for example, i have mine set up in samba with basic auth, the user that accesses the share has to be in the group "users"
there for, i mount the share the following way:
`net use x: \\192.168.0.4\Anime /persistent:yes /user:baine mypassword`
(note: not real user and password :P )

if the share is accessible by everyone (anonymous etc), then /user can be omitted :)
