### ISSUE TITLE
JMMServerPlex expresses title as "x-jat" instead of "en".  Make this a user option. 

### ISSUE THREAD

**Issue by bmfrosty** [japanesemediamanager/jmmserver#188]
See attached file.  Funny sorting is funny.

![badsort](https://cloud.githubusercontent.com/assets/31758/11265163/ca94523a-8e4e-11e5-86fb-d248f3f71390.png)

**Comment by bigretromike** [comment]
<3 kawaiiiiiiiiii
But to be honest - I know that when I fixed PlexImplementation there was a unhandled error with sorting function. Probably thats the case.

**Comment by bmfrosty** [comment]
Well.  The sorting seems to be in "en", and that's seems to be the way the XML is sorted, and I think that XBMC leaves the sorting that way.  The title seems to be the 'x-jat' title instead of the the 'en' title which is a sane default.  The title is always available in 'kanji' and 'x-jat' (which is the romanji of the 'kanji' title), and the 'en' version isn't always available.  In the client, at settings -> AniDB -> Language Preferences there's a place to set the preference order for the group list.  I suspect that the XML order is set by this (and I should test it sometime).  We just need the XML to prefer the title based on the same ordering.

**Comment by bigretromike** [comment]
Oh. I think also you refering about sorting made in nakamori plugin. Which is: Directories first, Video last. Which is simply - something with more than 1 episode is first, and then videos. Because when you enter Series you go inside directory with videos, and when you enter videos it start playing.

This is the way Plex feed information :-) and from now on Nakamori use other Instance than Plex use :-) and im working on feeding Nakamori with Directories only. This problem was related to PlexService, but after yestarday merge and Nakamori 1.0.5 is not PlexService problem. 

You can compile newest version of jmmserver to use latest nakamori plugin, or wait till @jmediamanager release it.

**Comment by bigretromike** [comment]
Currently if you go to "ALL" (currently in 1.0.5)
You have sorting by name which is displayed (A-Z) with Directories [A-Z] and Videos [A-Z].
I understand why this was made, but the XML tree is first searched for Directories nodes, then Videos nodes.

**Comment by bmfrosty** [comment]
Yes.  I think I'm explaining poorly, and didn't fully understand the
problem when I opened the issue.  What I'm talking about is that most
series have multiple names.  The sorting is something to be handled
separately.

5 Centimeters per Second is a great example.  In AniDB, let me give you 3
examples:

Main Title (x-jat) is:
Byousoku 5 Centimeter

Official Title in Japanese is:
秒速5センチメートル

Official Title in English is:
5 Centimeters per Second

The Main title is normally a romanji representation of the Official
Japanese title, I think.

I reads to me like the XML (I haven't checked out 1.0.5 yet) is sorted by
the Official en title, but displays the Main title.  Theoretically, Kodi
should sort the series alphabetically, but we should have the ability to
chose which for of title to prefer.  Since there's always a main title, it
makes sense to use that, but what I'm looking for is for it to be able to
pick the official english title if there is one, but if not, then use the
main title instead.

**Comment by bigretromike** [comment]
I dont see the problem to add this into plugin :-)
If this is the case please close issues here because its not a PlexService issue 
and open request at https://github.com/bigretromike/nakamoriplugin/issues :+1:
