### ISSUE TITLE
Job queue losing records when job queue is unpaused while still banned

### ISSUE THREAD

**Issue by SL-Gundam** [japanesemediamanager/jmmserver#193]
I'm currently Banned from AniDB due to me changing my entire AniDB library management from Anidb o'matic to JMM... was to be expected.
Every time i click the play button for the AniDB/General queue, JMM Server tries to execute a job. Gets a Banned error and pauses again. Again as expected.
The job JMM Server tried to perform is removed from the queue even though because of the ban the necessary data was not retrieved.

I think it would be better to either re-add the job back in the queue on failure or only remove it on success

**Comment by ElementalCrisis** [comment]
@hidden4003 fixes for timing in 3.6.5 should prevent this from happening. However users can still get banned by doing other AniDB related task while importing so we should look into disabling the start button and have JMM do a check once every hour and only enable the button once it can successfully connect. 

https://github.com/japanesemediamanager/jmmserver/issues/379

**Comment by hidden4003** [comment]
I think making job re-add itself is a potentially bad idea.

**Comment by hidden4003** [comment]
That is by design all of there requests can be repeated in one way or the other so it is not a big issue if it fails and gets deleted.
