### ISSUE TITLE
Adding files to 'input' folder don't results on moving them to 'output'

### ISSUE THREAD

**Issue by bigretromike** [japanesemediamanager/jmmserver#202]
Im having this issue few times now.

When droping series to 'input' folder the series is recognized, the files are linked properly and half of episodes go to 'output' folder into series folder, and the other half end up being in 'input' folder in the old folder.

Fun fact, the linked data have proper (real) path to file (so half of them have input half of them have output)

**Comment by bigretromike** [comment]
fun fact: It also rename folder name inside Input folder, but wont move it out

**Comment by bigretromike** [comment]
Is it because I have same episode for same series from different group ? Is that possible ?

**Comment by bigretromike** [comment]
looks so

**Comment by da3dsoul** [comment]
Open and close JMM server. I made a PR (the update images one) that also adds a drop folder rescan to the run import button. It doesn't fix the underlying problem, but it makes it easier to live with.

**Comment by da3dsoul** [comment]
After the PR is accepted, you won't need to restart the server, just run an import.

**Comment by ElementalCrisis** [comment]
@bigretromike Can you try to reproduce in 3.6? I just tried with an entire series and it moved both versions into the same folder, then tried with individual episodes and it moved them as well.

**Comment by bigretromike** [comment]
sorry, I wont probably have for that anytime soon - but if you tested, lets close issue and we will see if this issue occur any time sone
