### ISSUE TITLE
Question about MAL <-> AniDB Mapping

### ISSUE THREAD

**Issue by CtrlAltDefeat94** [japanesemediamanager/jmmserver#213]
I've been looking for a list/site that does mapping between MAL and AniDB for a while but I can't seem to find the place.

Where do you pull this info from?

Thanks in advance
CtrlAltDefeat

**Comment by ElementalCrisis** [comment]
JMM does the mapping with support from users. If MAL is enabled it will attempt to match the name automatically. This is not perfect which is where user submissions come in, if its linked wrong a user can override the link with the correct one.

**Comment by CtrlAltDefeat94** [comment]
Thanks for your reply. 
Is this data publicly accessible or stored locally?

**Comment by ElementalCrisis** [comment]
Yeah, if the setting is enabled (Settings Tab > Web Cache) MAL links can be downloaded and uploaded.

**Comment by AreFinstad** [comment]
on note on MAL and AniDB linking tho. i do think we need to add it to the community admin tab so we can link them permanently after a while.

**Comment by CtrlAltDefeat94** [comment]
After turning web caching on I got this error;
https://gist.github.com/CtrlAltDefeat94/d0306a139d982be7c50e

Is this some known issue or is something wrong in my configuration?

**Comment by ElementalCrisis** [comment]
What option dd you enable that gave you that error? I just turned them all on and off and don't see any errors in my log.

**Comment by CtrlAltDefeat94** [comment]
That is with all options enabled.

I'm unsure where the path "C:\Projects\GitHub\JMMServer\JMMServer\Providers\Azure\AzureWebAPI.cs" comes from. As this is not a valid path on my PC

**Comment by ElementalCrisis** [comment]
The path is from the build, don't worry about that. 

Are you still getting that error? What were you doing prior to getting the error?

**Comment by CtrlAltDefeat94** [comment]
Booted up JMM server and desktop -> let it run for a min or 2 -> error appears in log

I didn't touch anything, just let it run

**Comment by ElementalCrisis** [comment]
Well, you're getting a 400 response when sending your webcache data which wont break JMM. Maybe @jmediamanager can comment on this but I think its not a big deal unless you're seeing that error very frequently.

**Comment by CtrlAltDefeat94** [comment]
Is it possible to access these mapping records aside from with JMM? I'm trying to write a small script of my own where I would like to use these values(where relevant within my anime collection)
