### ISSUE TITLE
"Delete action" changed after update

### ISSUE THREAD

**Issue by SL-Gundam** [japanesemediamanager/jmmserver#217]
I used to have the option "Delete action" set to "Mark deleted" but after i upgraded from 3.4.6.2 to 3.4.6.4 the setting was set to "Delete file (local db)"

Any reason for this?

**Comment by ElementalCrisis** [comment]
Not on my computer but there should be another option for Marking Deleted. Pull Request #272 added two new options, Mark Unknown and Delete File (Local DB) though it probably should say Delete Locally. I changed the name because to me it made more sense but now I'm thinking not so much.

**Comment by SL-Gundam** [comment]
Yes there is another option but i reported this because its a possible upgrade issue. But i understand you cannot reproduce this.

I had 2 installations of JMM. Both had this issue

**Comment by ElementalCrisis** [comment]
Sorry, I was replying on my phone which is what I meant when I said not on my computer. The reason for your option being changed was caused by the those options being added and the re-arranging I did.

It went from

```
cboDeleteAction.Items.Add("Delete File");
cboDeleteAction.Items.Add("Mark Deleted");
cboDeleteAction.Items.Add("Mark External (CD/DVD)");
cboDeleteAction.Items.Add("Mark Unknown");
cboDeleteAction.Items.Add("Delete locally only");
```

To

```
cboDeleteAction.Items.Add("Delete File (AniDB)");
cboDeleteAction.Items.Add("Delete File (Local DB)");
cboDeleteAction.Items.Add("Mark Deleted");
cboDeleteAction.Items.Add("Mark External (CD/DVD)");
cboDeleteAction.Items.Add("Mark Unknown");
```

It was an oversight on my part, I overlooked the fact that if there was an already selected option, it would change what was selected when they were rearranged.

**Comment by SL-Gundam** [comment]
Yes very nice i figured that much

But what do we do?
1. Close this issue and ignore this issue
2. Update upgrade notes so that users know that they need to check this
3. Improve the upgrade from 3.4.6.2 to 3.4.6.4 so that it modifies existing settings properly (you must have a database update mechanism in place)
4. Something else

**Comment by ElementalCrisis** [comment]
I'll add some info about this on the blog post I posted about the new version. Should do the trick.

**Comment by SL-Gundam** [comment]
Well i just deleted something and it seems the dropdown box items do not match the applied action

After upgrade of JMM the setting was: Delete File (Local DB)
Changed it to: Mark Deleted
When i delete files through JMM the action applied is: Mark External (CD/DVD)

So i put it back to: Delete File (Local DB)
Now the action that is applied is: Mark Deleted

So now it really is a bug i guess
