### ISSUE TITLE
Plex Agent/Scanner to replace current plex plugin

### ISSUE THREAD

**Issue by saitoh183** [japanesemediamanager/jmmserver#218]
Im no programmer and i dont know the effort it would take to implement this but jmm is such a great piece of software that i said , it wont hurt to ask. :)

The idea is to have a plex agent and scanner that would use JMM as source for scanning in anime instead of the net (ie: hama agent) This way anime would be part of the native plex DB and each person could have there own watched status and people wouldnt have to give users access to the channel section so they can watch anime on plex. 

You could have a seperate plugin that could sync watched status with jmm (like the trakt plugin) and if you move files or or rename them, this probably wouldnt be a issue since plex already can pickup file changes and launch a rescan if need be.

For artwork and such, you could add the possibility of retrieving it from jmm, anidb,tmdb or the tvdb.( a bit like what the hama agent does).

**Comment by maxpiva** [comment]
I'll not doing this, maybe someone else can help you out. Currently plex is aimed to tv and movies and not anime. This channel with its limitations sort anime in the right way at least in my opinion. If no Dev will get this please close the issue

**Comment by saitoh183** [comment]
The plug-in does do a ok job but is not suited to properly support multiple users because you need to give users access to channels in plex which can be dangerous since you can't just give them access to the plug-in only

**Comment by da3dsoul** [comment]
Haha Shoko Metadata does this. Only took a year.

**Comment by Cazzar** [comment]
Just so people are aware if they ever come across it, I have written one of these: http://shokoanime.com/shoko-metadata/

**Comment by maxpiva** [comment]
Sync has been on and off several times with Shoko on Plex. Seems plex
developers have an internal struggle. If channels should support syncing or
not on channels, since most of the channel read content from the internet.
