### ISSUE TITLE
Delete action inconsistencies

### ISSUE THREAD

**Issue by SL-Gundam** [japanesemediamanager/jmmserver#220]
Related to issue: #217 

I deleted something and it seems the dropdown box items do not match the applied action

After upgrade of JMM the setting was: Delete File (Local DB)
Changed it to: Mark Deleted
When i delete files through JMM the action applied is: Mark External (CD/DVD)

So i put it back to: Delete File (Local DB)
Now the action that is applied is: Mark Deleted

So now it really is a bug i guess

**Comment by ElementalCrisis** [comment]
My fault, happened when I re-arranged the options. I fixed it and will be submitting a PR soon.
