### ISSUE TITLE
Virus found in current server download 3.4.6.4

### ISSUE THREAD

**Issue by efalsken** [japanesemediamanager/jmmserver#225]
![capture](https://cloud.githubusercontent.com/assets/253640/13267562/cee4b476-da32-11e5-873b-9da9c1d343a2.PNG)

**Comment by ElementalCrisis** [comment]
False positive, but needs to be looked into regardless. @jmediamanager can you take a look?
https://www.virustotal.com/en/url/a6078b95057bd799764e81b172ee0db4cb1c750bb98bd07169c4bccddc1dfcdd/analysis/1456286476/

**Comment by ElementalCrisis** [comment]
Closing, no other false positives have been reported.
