### ISSUE TITLE
Series marked as "Manually Linked" does not show up in library

### ISSUE THREAD

**Issue by morgenman** [japanesemediamanager/jmmserver#231]
Hello, I am runnning JMM Server 3.4.6.4.
I have one series (code geass R2) which absolutely will not show up in my library. 
![screenshot_5](https://cloud.githubusercontent.com/assets/3505950/13750401/9628dcec-ea05-11e5-9b49-9cade82c92ce.png)
It does however show up under "manually linked files" (I didn't manually link it at all). When I click the plus under each episode in the manually linked section, nothing shows up. (it should show the season its manually linked to). 
![screenshot_4](https://cloud.githubusercontent.com/assets/3505950/13750453/c813b27c-ea05-11e5-9b96-9c364717621f.png)
When searching for the files manually, it also gives me blank information
![screenshot_6](https://cloud.githubusercontent.com/assets/3505950/13750469/da10f872-ea05-11e5-8b08-1f225abb4df8.png)
I have tried removing and readding, rescanning all my files, renaming and then readding them, manually specifying the folder.. etc etc.

**Comment by AreFinstad** [comment]
im not certain if this will fix it but.
try deleting the series in the JMM Series page (in collection for example)
and if you are certain the files are in your folder then just re-import it again.
worth a shot anyway, you can always join in on the Discord server here and ask in the support chat!
https://discord.gg/0XKJW7TObKLajoKc

**Comment by morgenman** [comment]
I've tried doing what AreFinstad recommended. I even went so far as to rename all the files with filebot and rebuild the database with mysql. 
The issue persists, and it appears to now affect a few more shows

**Comment by morgenman** [comment]
I was poking around the database (mysql now) and found that under "crossref_file_episode", the animeID is listed as 0 for the problem episodes. Not sure if this helps. 
![image](https://cloud.githubusercontent.com/assets/3505950/13917089/f215cfe8-ef5e-11e5-81f1-9f3863cf024e.png)

**Comment by morgenman** [comment]
OK! I found a fix!
find your episodes in mysqlworkbench (or whatever you use to edit the db) and navigate to the workbook "crossref_file_episode".
Find your episodes. (the crossrefsource will be 3 and the animeid will be 0) 
delete the rows
And bam upon refresh they are in your unrecognized tab of jmm, ready for actual manual linking.

**Comment by da3dsoul** [comment]
So a nice feature/fix would be to check for this on run import and re scan it.

**Comment by ElementalCrisis** [comment]
I believe @Baine fixed this issue awhile back.

**Comment by ElementalCrisis** [comment]
Fixed in 3.5.0.1
