### ISSUE TITLE
Add a way to reopen AniDB login details dialog

### ISSUE THREAD

**Issue by OronDF343** [japanesemediamanager/jmmserver#232]
When you first set up JMM Server it shows a dialog that lets you log in to AniDB. Currently there is no way to bring back this dialog if it was closed.

**Comment by da3dsoul** [comment]
Sure, it would be nice, but you can do this with JMM Desktop

**Comment by ElementalCrisis** [comment]
While you can make the change in JMM Desktop, there are some people who rarely if ever use it. When my schedule clears up in a fee weeks I'll take a look and see if I can add this.

**Comment by da3dsoul** [comment]
Ah, I keep it installed and run it periodically as while JMM is immeasurably useful, it is by no means flawless

**Comment by ElementalCrisis** [comment]
Had a free moment so I added this, will see if I can get it into 3.5.

**Comment by da3dsoul** [comment]
This is done, right?

**Comment by ElementalCrisis** [comment]
Yep, I added it earlier this week.

**Comment by da3dsoul** [comment]
Thought so, I guess @jmediamanager just hasn't gotten around to closing this

**Comment by ElementalCrisis** [comment]
Oh I can close the issue. I was just waiting till 3.5 launches but I guess there's not harm in closing it now.
