### ISSUE TITLE
"Initializing Queue Processors..." non-stop

### ISSUE THREAD

**Issue by bigretromike** [japanesemediamanager/jmmserver#241]
I was thinking this was related to #239, but Im using 2 versions of JMM Server, stable one and dev. Both use same mysql database.

The 3.4 works alright and 3.5 stuck on this message and thanks to that I have only "Setup" tab in 3.5.

**Comment by jmediamanager** [comment]
@ElementalCrisis Could you fix this one please
It is actually not stuck on the processors, it is actually doing the stats, but the message is incorrect.

**Comment by jmediamanager** [comment]
NOTE - this is the reason I added options to disable Plex/Kodi.

**Comment by ElementalCrisis** [comment]
Sure, I'll fix this when I get home.

**Comment by jmediamanager** [comment]
NOTE 2 - This will not fix the amount of time it takes for JMM Server to start. It will only fix the message that is shown.

The underlying problem is how long the Kodi stats take.

**Comment by bigretromike** [comment]
Ohh good to know its not that thing it have message for and I will love the disable/enable option

**Comment by jmediamanager** [comment]
Those options are available in the source now
And I think @ElementalCrisis has fixed this as well?

**Comment by ElementalCrisis** [comment]
Yeah, should show the correct language string now.

**Comment by bigretromike** [comment]
The checkbox are added but dont work even after restart

**Comment by bigretromike** [comment]
ok they semi work, service still works but is not populated. This is the intended way ?

**Comment by jmediamanager** [comment]
What do you mean they are not populated?

**Comment by bigretromike** [comment]
I mean that I can query service via http but results look like the database is empty. I was thinking that disable plex/kodi service will just disable it and it will 404 or throw error that page was not found.

But this option just disable populating cache with data and not disable those service entirely

**Comment by jmediamanager** [comment]
Yeah, I think just disabling the cache is good enough.

If you are disabling those options, you have no plans to use those apps in the first place, so not really an issue.

**Comment by bigretromike** [comment]
Yes, but wouldn't it be better to not start service at all to save resource ?
