### ISSUE TITLE
A way to disable AniDB communications.

### ISSUE THREAD

**Issue by naarcissus** [japanesemediamanager/jmmserver#246]
I would like a way to temporarily disable all communications with *AniDB* so as not to extend bans, but to be able to continue using JMM.

**Comment by da3dsoul** [comment]
The pause button in server. The queue is labeled general, but that is because the queue is shared with MAL, TVdb, etc. Separating the queue would be moot as well, as the show info needs to be scraped from AniDB before it can be looked up elsewhere.

**Comment by naarcissus** [comment]
Ah. Thank you. I totally spaced the unassuming pause button.
