### ISSUE TITLE
Series/Episodes appear as unwatched in Collection after re-creating all groups

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/jmmserver#25]
**Reported by aznzhang, Aug 24, 2012**

The option I am referring to is in the Essential tab of JMM Desktop. Upon checking the option and clicking "Recreate All Groups," and then refreshing in Collection, series that I have watched in AniDB show up as unwatched.

**Comment by ElementalCrisis** [comment]
I'm unable to reproduce this bug, going to assume it was either something on the users end or fixed in a newer version of JMM.
