### ISSUE TITLE
Groupfilters, cachestats and Anime Updates performance is subpar

### ISSUE THREAD

**Issue by maxpiva** [japanesemediamanager/jmmserver#251]
On big collections, perfomance is subpar. Migrating the database to NOSQL and redo the whole system is a nono right now for me (No time).

So is time for plan B.

* groupfilter precalculations stored in DB.
* Optimize DB indices if possible.
* More intelligent approach to Anime Updates. (Recalculate less information).
* Stats Cache converted to a Group View Cache stored in the db, in a common format (class) that satisfy all clients.

**Comment by maxpiva** [comment]
Unable to assign this to myself op pls.

**Comment by da3dsoul** [comment]
I believe the point of stats cache is to keep some data in RAM, rather than db. RAM is faster than any disk. Sure, it would be nice to organize it better and make it store values, rather than recalculating all of it on every start and repeatedly during run. Some things only need to be calculated once, so the recalculation of it all the time is just wasteful.

**Comment by maxpiva** [comment]
Stat cache is a mess right now, Group Filters, plex and kodi loading take
ages on startup. You don't have to explain to me what stat caches does, i
coded part of it, i know this project inside/out, i'm the one responsive of
that slowdown.

**Comment by da3dsoul** [comment]
Oh, okay. I thought you were saying do away with StatsCache entirely to be part of the db. I understand the db can be configured to be just as nice as what StatsCache is supposed to be, but I have no idea how to do it effectively, and I know I'm not alone on that (after all, the guides on jmm setup exist for a reason).

**Comment by maxpiva** [comment]
In fact, this change will kiss goodbye the statCache.

StatCache, currently is used for: Cache Calculated stats, Cache AniDB_Contracts, Plex Contractas and Kodi Contracts, and indexing groupfilters with a dictionary for fast access.

The calculated stats are not needed anymore because AniDB_Anime, AnimeSeries, AnimeGroups will have an up to date Contract always to be feeded directly to the client who asks, and stored as JSON in the database. Every change on the above Entities, will reflect the change on save on the contract.

Groupfilters will also cache The corresponding User/Groups assigned, and also will store that information as json in the database.

This will eliminate the need to recalculate all stats, since they're already cached in the database.

Also, all the serialization/deseralization and database queries to generate those contracts, are in fact executed when the entity changes (update or save). So clients doing queries over those entities, will get a speedup, since the contract is already pre-generated.

**Comment by maxpiva** [comment]
Fixed by #257
