### ISSUE TITLE
Only wait for the AniDB ban protection if actually getting from AniDB

### ISSUE THREAD

**Issue by da3dsoul** [japanesemediamanager/jmmserver#252]
Rather than HTTP cache. I did an import as I'm migrating to SQL Server from MySQL, and it still waits, even though it's not actually pulling from AniDB. I checked that it wasn't pulling AniDB through my router. Because, well, last I checked, it doesn't take 2 seconds to retrieve a few kb from an ssd...

**Comment by da3dsoul** [comment]
@maxpiva do you think you can look into this for your db cache pr? It'd make importing so much faster

**Comment by maxpiva** [comment]
The Cache is a 2nd level memory cache it stores common database queries and
entities in memory. So there is no round trip to the db. I don't think
it'll accelerate the import only marginally.

**Comment by da3dsoul** [comment]
When you import/rebuild database, it scans your AniDB HTTP  cache. The problem is that it waits the 2 seconds to prevent getting banned, even though it never attempted to pull from AniDB. In the 2 seconds it waits, it could be done with 10 more files. That is why it would make it faster. Only the first run after updating to your new system would be faster by much, but that's the one that'll take awhile. If you don't think it'll be a big deal, then okay.

**Comment by da3dsoul** [comment]
Upon closer inspection, it still pulls using udp for file import, so this is not applicable
