### ISSUE TITLE
Long Initializing/Populating after start

### ISSUE THREAD

**Issue by bigretromike** [japanesemediamanager/jmmserver#255]
It takes more than 10 minutes with 1200+ series to be accessible via API (not sure about JMMD)
Can we optimize this anyway ?

**Comment by ElementalCrisis** [comment]
Does disabling Plex in settings in JMM Server help at all?

**Comment by maxpiva** [comment]
Already done. took 10 seconds startup with ~4000 series, with plex and kodi included. You have to wait till i finish #251. Expect mayor speedups on various areas also. 

Op please Close this issue and leave #251 open, since it's duplicated.

**Comment by ElementalCrisis** [comment]
That's awesome @maxpiva!
