### ISSUE TITLE
JMM Server 3.5.0.1 does not start

### ISSUE THREAD

**Issue by pandabuilder** [japanesemediamanager/jmmserver#260]
After updating to 3.5.0.1, my JMMServer process starts for a second (I see it on the Task Manager), and then closes. No log entry is updated.

Windows 10 x64.

**Comment by jmediamanager** [comment]
Hi, we are looking at this right now

**Comment by jmediamanager** [comment]
If you re-download and install it should now work
http://www.jmediamanager.org/latestdownloads/JMM_Server_Setup_3.5.0.1.exe.zip

**Comment by jmediamanager** [comment]
NOTE - One file was missing from the installer

**Comment by pandabuilder** [comment]
You sure it's working? It still closes after opening.

**Comment by jmediamanager** [comment]
yeah definitely working for me now.
I have just uploaded 3.5.0.2 (missing language files)

Maybe install that and give it another go

**Comment by pandabuilder** [comment]
Thanks man, version 3.5.0.2 works, 3.5.0.1 was not.
Cheers.
