### ISSUE TITLE
Add new file extension (M4V)

### ISSUE THREAD

**Issue by smjameel93** [japanesemediamanager/jmmserver#265]
I have noticed that currently M4V files are not recognized, renaming the files to MP4 does the trick, nevertheless, having the original file extension is a far better choice.

**Comment by da3dsoul** [comment]
Just add it in the settings

**Comment by da3dsoul** [comment]
I believe this is fixed

**Comment by ElementalCrisis** [comment]
Was it added in the default list?

**Comment by da3dsoul** [comment]
I think so

**Comment by da3dsoul** [comment]
Oh, no it was only mk3d. Whatever I'll get this as it'll take seconds.

**Comment by da3dsoul** [comment]
There it's in pr

**Comment by ElementalCrisis** [comment]
Added in version 3.6.0.1.
