### ISSUE TITLE
Images dont refresh on ui after downloading.

### ISSUE THREAD

**Issue by craige1** [japanesemediamanager/jmmserver#270]
When using the features like get missing data, the ui used to update the missing images once downloaded. This doesn't happen anymore and the user must press refresh series information button to get the pictures to load.

**Comment by Rand-Random** [comment]
I noticed that this is only the case with the first image.
So when you hit the button "get missing data" in situations where multiple images are missing the first goes black but the other work just fine.

**Comment by craige1** [comment]
moved to client
