### ISSUE TITLE
JMM hashing speed is very low again

### ISSUE THREAD

**Issue by SL-Gundam** [japanesemediamanager/jmmserver#272]
Hi
I updated 3.4.6.4 to 3.5.0.2 two days ago
It seems the new 3.5.0.2 has the slow hashing speed issue again. The hasher.dll is also double the size again compared to what the proper ones sizes were. Any reason why the old hasher.dll is packaged with the installer again?

Earlier issue about this: #187

**Comment by ElementalCrisis** [comment]
This was mentioned on Discord, was discovered that the x86 and x64 debug versions of hasher.dll were included in the release.
