### ISSUE TITLE
JMM Server HTTP services not starting if launched as user

### ISSUE THREAD

**Issue by hidden4003** [japanesemediamanager/jmmserver#287]
First I ran it as administrator, firewall exceptions created etc. As admin requirement was removed so I am now able to run it as a user.
Cache is being built fine and then I get:
"HTTP could not register URL http://+:8111/JMMServerImage/. Your process does not have access rights to this namespace (see http://go.microsoft.com/fwlink/?LinkId=70353 for details)."

Pressing "Shutdown" in this state also throws a several "JMM Server has stopped working" errors, those are probably exceptions from trying to shutdown HTTP services that didn't actually start.

**Comment by da3dsoul** [comment]
Server so needs to be run as admin for multiple reasons. Client does not

**Comment by hidden4003** [comment]
Plex, UMS, Kodi and other similar software all run without admin permissions.

**Comment by da3dsoul** [comment]
The reasons are fixable, but as of now it still does. It stores things in the program folder and does not follow the proper method of starting connections on all adapters to name the ones I can think of

**Comment by hidden4003** [comment]
This particular issue can be fixed in 3.6 the other one regarding storage will require more work.
It looks like all we need to fix this is to add something like this into the server itself or installer:
`netsh http add urlacl url=http://+:8111/JMMServerImage user=DOMAIN\user`

**Comment by bigretromike** [comment]
wasn't this added already to installer ?

**Comment by hidden4003** [comment]
I did run the server as admin, changed the port around and it created all the rules, but still launching as user now results in a message "Access denied".

**Comment by ElementalCrisis** [comment]
Try building the installer and installing 3.6 as opposed to just compiling it. I believe its been fixed that way.
