### ISSUE TITLE
Error message that JMM Server is already running

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/jmmserver#291]
In JMM Desktop if you have the option selected to start JMM Server when JMM Desktop starts, you will get the following error message 'JMM Server is already running'.

JMM Desktop should check if JMM Server is already running before it tries to start it again.

**Comment by da3dsoul** [comment]
This is fixed, correct? @ElementalCrisis

**Comment by ElementalCrisis** [comment]
This option does not even work for me.

**Comment by da3dsoul** [comment]
Well I thought someone at least fixed the pop up. No idea if it works. For one, it definitely only works if ran from local host, as I'm pretty sure you already need a running process to start the server on the host

**Comment by ElementalCrisis** [comment]
Oh yeah the pop-up message is now logged, but the issue @jmediamanager is talking about is the error message JMM Server gives you if you try to open another instance of it while it's already running.

**Comment by da3dsoul** [comment]
Yes. It doesn't do that anymore, correct?

**Comment by ElementalCrisis** [comment]
I can't reproduce because I can't get the option to even work. Though that error message is still there if you manually open two instances of JMM Server.

**Comment by da3dsoul** [comment]
Whether it works out not is a different issue. We can close this if the message doesn't pop up

**Comment by da3dsoul** [comment]
Ah

**Comment by jmediamanager** [comment]
Fixes as part of this commit

https://github.com/japanesemediamanager/jmmclient/commit/f8237ec06b25102bf0dc65a9d3a2d7aefd4963e7
