### ISSUE TITLE
JMM Desktop Not Moving Downloaded Files Over

### ISSUE THREAD

**Issue by antking83** [japanesemediamanager/jmmserver#305]
Greetings,

Been using JMM for quite a few years now and have been loving it.  Currently, I've seem to have a issue where after I've downloaded some anime, pressing the import button doesn't move the files over like it traditionally has.  I'm familiar with the work flow that if it wouldn't move over automatically, that I could use the unrecognized method and manually link the files to the series.  Unfortunately, I'm unable to use that either.  Take Naruto Shippuuden for example, If I were to go and try to link it manually, the number episodes in the drop down menu only goes until 454 when I have the next ten or so episodes after that ready to move over.

I've also found that I'm  unable to sign in to the AniDB through the JMM desktop or server.  I've confirmed that my log in credentials work as I'm able to log in directly to the AniDB website.  I thought the port might have changed but I'm unable to find out otherwise if that's the case and if so, what to change the port to.

I've attached both logs I have to better help in trouble shooting this.  i would appreciate any help that can be provided.

Thank you

[2016-07-07.txt](https://github.com/japanesemediamanager/jmmserver/files/353282/2016-07-07.txt)
[2016-07-07.txt](https://github.com/japanesemediamanager/jmmserver/files/353280/2016-07-07.txt)

**Comment by ElementalCrisis** [comment]
Hello, 

AniDB has been having server issues which is what we use to compare hashes and update series information. Until they are completely running again some functionality may not work. As of yesterday there was no ETA for when their API server.

https://twitter.com/AniDBStatus

**Comment by antking83** [comment]
No problem lol.  I just wanted to make sure there wasn't anything I could do on my end.  Thank you for the update.

**Comment by ElementalCrisis** [comment]
Looks like the API Server is up and running agian.

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">apis are back up and running. requests might be slow right now as a lot of import/export/stat crons are running as well.</p>&mdash; AniDB Status (@AniDBStatus) <a href="https://twitter.com/AniDBStatus/status/751486008248700929">July 8, 2016</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
