### ISSUE TITLE
Option to Autostart JMM Server

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/jmmserver#31]
**Reported by rickyvh001, Nov 12, 2012**

The ability to have JMM Server autostart when Windows loads up would be a nice addition. 

**Jan 14, 2013 inferknox**

In this regard, perhaps a button could be added next to the "Minimise on Startup" button, on the "Settings" tab of JMM Server, that would use the same method as is used by MSI Afterburner, of creating in "scheduled task" to run JMM Server with "highest privileges".
I created such a scheduled task and set JMM Server to "Minimise on Startup", and it's been auto-starting flawlessly at login.

For reference, I've attached an .xml export of the scheduled task I created to run JMMServer at login (if you wish to import it, make sure to edit the file with notepad & change the "YourPC" & "YourUserName" by the UserID field, to those specific to your system).

**Comment by ElementalCrisis** [comment]
Marked as In Progress, no built in feature yet but possible if you follow the guide on the site. 
http://jmediamanager.org/jmm-server/configuring-jmm-server/#jmm-start-with-windows
