### ISSUE TITLE
Adding TVDB crossref takes a long time 

### ISSUE THREAD

**Issue by hidden4003** [japanesemediamanager/jmmserver#321]
Found this while investigating client issue:
https://github.com/japanesemediamanager/jmmclient/issues/418

My suggestion would be to make a separate command for that and additionally implement batch mode to reduce the amount of updates.

**Comment by ElementalCrisis** [comment]
Referencing back to my original issue, here's I show I added awhile back that only lists 1 TvDB link.

![jmmdesktop_2016-07-23_16-52-44](https://cloud.githubusercontent.com/assets/9443295/17080881/ea1234be-50f5-11e6-9c90-b61f02dcba3f.png)

However there are actually 5 TvDB Community links available.

![jmmdesktop_2016-07-23_16-53-38](https://cloud.githubusercontent.com/assets/9443295/17080886/078419fe-50f6-11e6-9a62-5ec89cc7b9a1.png)

Besides the top one, the other ones are not being added which means I don't get the updated linking that was already available. I would have to go through each of my shows and manually update the linking for it to be correct.

**Comment by hidden4003** [comment]
The original issue was that it was autolink not adding all the links, I didn't check that part. It will only work if anime doesn't have any links, it there is a link already it will not delete xrefs and relink as manual popup does.
