### ISSUE TITLE
New Drop Destination Not Being Used

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/jmmserver#329]
How to reproduce. 

1. Create folder and only set it to "Watch For New Files".
2. Create a drop source and a drop destination, set each to "Watch For New Files" as well.
3. Drop some files in drop source.
4. Once files have been moved into original drop destination change drop destination.
5. Drop some files in drop source.
6. Files should go to new drop destination but end up in the first folder we added back in step 1.

Additionally, adding a new drop destination or reusing the original one does not work either. As far as I can tell you're no longer able to select a drop destination.

**Comment by hidden4003** [comment]
For an existing series files are moved to the folder where the latest episode is located, regardless of drop source.
