### ISSUE TITLE
Log rotator

### ISSUE THREAD

**Issue by bigretromike** [japanesemediamanager/jmmserver#340]
As I look thru log files for #226 I found out that logs from importing collection are taking up 500Mb 😱 
Daily logs from now doing anything are 7-8mb
Also I have there logs from 2015... Maybe we could add log rotator, that would zip logs older than week, and delete older than month ? or even 3 days / 7 days rotate cycle, as we don't need logs from week ago, and most of the time they are use to help out people with problems.

Or we could add settings to not log every command that is process

**Comment by ElementalCrisis** [comment]
I agree, my suggestion is something like the following with these default settings

Basic Settings - Enabled by Default

Compress Old Logs? - Yes
How Often? - Weekly
Delete Older Logs? - Yes
How Often? - Every 3 months

This makes it part of the minimal setup for new users and users wanting to customize things can change the settings.

**Comment by bigretromike** [comment]
I aggree that would be great, as more advance user could save space and less advance users could have log to submit with issues.

**Comment by bigretromike** [comment]
please don't force new features before schedule

**Comment by maxpiva** [comment]
Seems Elemental put it in for 3.6.5 and I, assigned you :P

**Comment by bigretromike** [comment]
And I reassing it to 3.7 and left it to me :-)

**Comment by bigretromike** [comment]
https://github.com/japanesemediamanager/jmmserver/commit/b204cba7859748047b6a2fc7c4c8ee3cd9fa34b3
