### ISSUE TITLE
Move File Does Not Use Preferred Language Names

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/jmmserver#356]
When using a Drop Source and Drop Destination, any files moved will be placed into a new folder that uses the series Main Title instead of the title based on the preferred language selected.

**Comment by da3dsoul** [comment]
Look at the way I get titles in the regroup or rename functions. It is more accurate, as it will use TVDb if necessary

**Comment by ElementalCrisis** [comment]
Will do.
