### ISSUE TITLE
Watched Filters (has watched and has unwatched) don't update contracts on change

### ISSUE THREAD

**Issue by da3dsoul** [japanesemediamanager/jmmserver#359]
As title States. It updates in JMM client, but for Kodi/Plex they don't

**Comment by da3dsoul** [comment]
I discovered it's an issue with the watch states not persisting after some unknown change (I haven't figured it out yet)

**Comment by da3dsoul** [comment]
The filters update if 'watched', but then revert later

**Comment by maxpiva** [comment]
Did this have something to do with sending the wrong episode id to the Kodi Signature?

**Comment by da3dsoul** [comment]
It did, but then once fixed, I noticed it won't persist. I think restarting the server will reliably make it revert, but I didn't figure out what else did, as after awhile, it would just happen. Adding a new episode might be the cause

**Comment by maxpiva** [comment]
will look into

**Comment by da3dsoul** [comment]
Restarting the computer definitely causes it. I don't get why restarting the server didn't cause it

**Comment by maxpiva** [comment]
Can anyone replicate this, if yes, please reopen

**Comment by da3dsoul** [comment]
It only happens on rare occasions and fixes itself after a bit. I think it is a transaction issue, but yeah rare and hard to replicate.
