### ISSUE TITLE
'Continue watching' generate wrong url

### ISSUE THREAD

**Issue by bigretromike** [japanesemediamanager/jmmserver#371]
Using 3.5.x.x when local pc start watching series and init the serie to show up in "continue watching" and remote client ask for those, jmmserver return url with localhost in them as those url was used for creating them. 
Why do you store url ? cant you make it dynamic/regenerate in fly ?

**Comment by maxpiva** [comment]
First, in what context Could you be more specific. In case Kodi/Plex all key/url are dynamic generated. I don't follow the line of thinking of continue watching... If you list Continue Watching Filter (the url will only say -> GetFilters -> this filter id, for this user) it'll return a list of Series that have already been watched, at least one episode to watch and order by episode date desc. There is nothing to init. The filter result was already calculated last time one of those 3 factors changed. When you make some episode as watched, the filter will be recalculated.

**Comment by bigretromike** [comment]
is this in 3.5 or you referring to 3.6-beta?

**Comment by maxpiva** [comment]
Ahh. But why reporting something that will be fixed or changed in 3.6?

**Comment by bigretromike** [comment]
I dont know. Im using latest 'stable' version which happend to have bug. So as it stable im reporting bug that exist and maybe is copy-paste to new version. thats why im posting it. if its fixed please close it.

**Comment by maxpiva** [comment]
I don't fully understand the question in the first place :P

**Comment by bigretromike** [comment]
Sorry, i'm unable to install unstable version on remote computer
My original question was: Does url for items inside that filter are stored or made in fly.

**Comment by maxpiva** [comment]
Hmm Good question, if my memory serve my right, they were pre-cached in the deprecated StatsCache.

**Comment by bigretromike** [comment]
so it can be a 3.5 thing then if there is no StatsCache in 3.6

**Comment by maxpiva** [comment]
Yup, deprecated in 3.6.
Currently links are recalculated when they need to render. They might end in the PlexKodiContractCache inside the database, but that particular part (key) will be recalculated.
