### ISSUE TITLE
Can I delete Stored SQlite Database Now

### ISSUE THREAD

**Issue by Adyel** [japanesemediamanager/jmmserver#375]
Hello there,

I used SQlite Database for a while now I am switching to MySQL. I am doing the Re HASH now. Can I delete the old Database ? "E:\Program Files (x86)\JMM Server\SQLite\JMMServer.db3" (FYI: All of my software are located on NON SYSTEM DRIVE)

I have another question. Where is MySQL Database Located ? I don't want to Re HASH My collection Everytime I Setup Windows (Yes, I do it time to time). Can I reuse the old DB when I reinstall OS ? or maybe switch computer.

**Comment by ElementalCrisis** [comment]
Yeah you can delete the .db3 file. You're MySQL database should be in C:\ProgramData\MySQL\MySQL Server 5.6\data.

**Comment by Adyel** [comment]
Can I re use the Database after OS Installation or Need to Re HASH again ?

**Comment by ElementalCrisis** [comment]
Sure.

**Comment by da3dsoul** [comment]
This looks closeable. Reopen if you need further assistance.
