### ISSUE TITLE
Installer fails to launch JMM Server after installation

### ISSUE THREAD

**Issue by OronDF343** [japanesemediamanager/jmmserver#382]
The installer fails to launch JMM Server because it requires elevation. Maybe the `runascurrentuser` flag can fix this?

**Comment by ElementalCrisis** [comment]
Yeah its been an issue for awhile now. I'll mess around with the installer and see if we can get it working or at least remove it.

**Comment by yhoogi** [comment]
An idea when it will be applied to the release?

Cheers,

**Comment by ElementalCrisis** [comment]
Fixed and tested, when 3.6.0.3 becomes available in a few hours please let me know if it works for you.

**Comment by hidden4003** [comment]
Works, checked in 3.6.1.0
