### ISSUE TITLE
Nancy's Branch Was Not Up to Date

### ISSUE THREAD

**Issue by da3dsoul** [japanesemediamanager/jmmserver#398]
At least my changes to the legacy api which allowed nocast and watching of groups and series are not included. That's at first glance.

**Comment by da3dsoul** [comment]
Also, what is this obj folder? it looks like an incomplete bin.

**Comment by bigretromike** [comment]
obj is some trash, dunno why git suddenly added that.
also your fixes went missing before legacy api is created on top of nancy - which I warn before ... 
if it been merge before this wouldn't happend as you would work on nancy-like functions

**Comment by ElementalCrisis** [comment]
Is this still an issue?

**Comment by da3dsoul** [comment]
Yep, I'll need to look over APIv2 and rewrite it for both

**Comment by bigretromike** [comment]
APIv2 dont have images yet as both needed to shear anyway

On September 15, 2016 2:53:47 PM GMT+02:00, da3dsoul <notifications@github.com> wrote:
>Yep, I'll need to look over APIv2 and rewrite it for both
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/japanesemediamanager/jmmserver/issues/398#issuecomment-247319625

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bigretromike** [comment]
Wrong issue, sorry ;-)

On September 15, 2016 1:50:44 PM GMT+02:00, ElementalCrisis <notifications@github.com> wrote:
>Is this still an issue? 
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/japanesemediamanager/jmmserver/issues/398#issuecomment-247307108

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bigretromike** [comment]
@da3dsoul you rewrite nocast, right ?:-)

**Comment by da3dsoul** [comment]
Yep. Just add /nocast before the extension. Works on legacy API and v2

**Comment by bigretromike** [comment]
So we can close this :-)

On October 9, 2016 3:50:34 PM GMT+02:00, da3dsoul <notifications@github.com> wrote:
>Yep. Just add /nocast before the extension. Works on legacy API and v2
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/japanesemediamanager/jmmserver/issues/398#issuecomment-252487467

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
It looks like it
