### ISSUE TITLE
Moderation of Community submitted links

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/jmmserver#40]
Sometimes users will submit links for TvDB / MAL/ Trakt etc, which are incorrect.

Create functionality to edit these links (must be authenticated)
- UI in JMM Desktop
- Ability to mark a community recommendation as 'Moderator Approved'
- Only available to authenticated users (authed at server end)

**Comment by ElementalCrisis** [comment]
Already implemented.

**Comment by AreFinstad** [comment]
@ElementalCrisis false, its only supported by tvdb and trakt. not MAL or the movie database.
the ground work is there but not everything in this issue is supported just yet IMO.
