### ISSUE TITLE
pull and sync scrobble progress before playing (or sync often)

### ISSUE THREAD

**Issue by AreFinstad** [japanesemediamanager/jmmserver#407]
the trakt api supports scrobbling progress. you can pull that progress from the site and use that in another program.

so you can start watching something in one client and start from the moment you left off on another client if its synced up.

tested this many times myself with popcorntime and plex where i could start a movie on popcorn and finish it on plex or whatever.

this would allow us to continue on any device that supports it.
plex plugin support is deeply wanted!

**Comment by RickDB** [comment]
Fixed Trakt sync and added scrobble support which will solve this issue :)

Still needs client support for scrobble but My Anime 3 will have it later today and JMMDesktop shortly after where it will send playback status every 15s.
