### ISSUE TITLE
Cache not being populated

### ISSUE THREAD

**Issue by bigretromike** [japanesemediamanager/jmmserver#418]
I had 3 items in db
added 2 more (via cloud)

this code dont do anything as GetAll see no items in cache.

```
AnimeEpisodeRepository rep = new AnimeEpisodeRepository();
                return rep.GetAll();
```

**Comment by maxpiva** [comment]
Unable to reproduce, are you sure your database is allright?. Does the log file shows any error?

**Comment by bigretromike** [comment]
Db is new. Will look into. Hope its just db patch error , but restarts didnt helped 

On September 14, 2016 3:34:31 PM GMT+02:00, Maximo Piva <notifications@github.com> wrote:
>Unable to reproduce, are you sure your database is allright?. Does the
>log file shows any error?
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/japanesemediamanager/jmmserver/issues/418#issuecomment-247014184

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bigretromike** [comment]
I send you a db dump. check yourself

**Comment by bigretromike** [comment]
Been 3 days, if there was a cache problem its probably fixed by repofactory by now
