### ISSUE TITLE
IRC search

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/jmmserver#42]
**Reported by Craige1Emmott, Jan 14, 2013**

Because the main release channel of anime is IRC.

**Jan 15, 2013 imperialxt**

Not so much anymore. This would require a built in irc/xdcc client? Running a fansub group and helping a few others. We all release torrents at the same time we do the bots or soon after.

**Jan 20, 2013 werndlymob**

Yeah I agree that torrents are the main source of downloads now.
While IRC would be useful, it also seems like a lot of effort.
Unless you're volunteering to do the work craig ;)

**Jan 21, 2013 Craige1Emmott**

Yeah, its something I was planning to do in my anime 2. I might as well give it a shot now :)

**Comment by ElementalCrisis** [comment]
While IRC is still popular, sites like Nyaa, BakaBT and Animebyt.es have made the need for IRC for anime no pointless.
