### ISSUE TITLE
Comprehensive logging for Nancy

### ISSUE THREAD

**Issue by da3dsoul** [japanesemediamanager/jmmserver#420]
It does not seem to log anything, and it's making debugging quite difficult

**Comment by bigretromike** [comment]
You added debug console + you can enable tracking url there without problems. 
What debuging would you like to have ?
We could add a custom handler like its for 404 when there is a 500 Code it will log it, but then we need to put error with proper codes. Or anything other than 200 would be handle there. It all depend if we want to use NLog or something else for log clean

**Comment by da3dsoul** [comment]
If there is an actual error with Nancy itself, it didn't seem to log. That's what I mean. A way to forward Nancy logging.

**Comment by bigretromike** [comment]
the only problem that I currently had was bad path to api call etc, or not uac port but that was already resloved. Any examples?

**Comment by da3dsoul** [comment]
If, due to whatever reason, it can't do what it needs to. Like netsh issues, blocking from antivirus, etc.

**Comment by bigretromike** [comment]
netsh is handled :-) but it should be easy as you add logger in same place where the netsh is handled for nancy in try before startnancy()

**Comment by da3dsoul** [comment]
It's 4 lines to make this happen...

**Comment by bigretromike** [comment]
wasn't this done, or current debug consol for nancy isnt the solution ? @da3dsoul

**Comment by da3dsoul** [comment]
Yes done closed
