### ISSUE TITLE
Obey 'Apply at Series Level' for Kodi and Plex

### ISSUE THREAD

**Issue by da3dsoul** [japanesemediamanager/jmmserver#431]
Currently, for filters, it gives the whole group, rather than what matches.

**Comment by da3dsoul** [comment]
Okay, currently no info on what filter you are under is provided to JMM, and thus it can't filter. We'll need an API that allows for passing the current filter (which we can pass along in Nakamori or Plex plugin), and will in turn filter out series where needed.

**Comment by da3dsoul** [comment]
This is done. I can continue testing Nakamori when the api is fixed @bigretromike

**Comment by bigretromike** [comment]
That fix is for issue https://github.com/japanesemediamanager/jmmserver/issues/502

**Comment by bigretromike** [comment]
#502 is Closed

**Comment by da3dsoul** [comment]
Cool I'll test when I get home

**Comment by bigretromike** [comment]
Why you needed this ? To be precise what this do ?:-)

**Comment by da3dsoul** [comment]
Are you familiar with how 'Apply at Series Level' works? Basically, it only shows series that meet the filters requirements, rather than the entire group. This only makes a difference for grouped series.

**Comment by bigretromike** [comment]
oh - ok, I don't use grouped as I cannot set it via Kodi ;-) hahaha
You can probably close this one as its not on Nakamori side to support it ;-)

**Comment by da3dsoul** [comment]
hehe you haven't looked, ha ve you? I already wrote it. Grouping settings are purely a server setting. It was only in Desktop before, but it should make it into the webui.
