### ISSUE TITLE
Nancy JMMServerImage not working

### ISSUE THREAD

**Issue by da3dsoul** [japanesemediamanager/jmmserver#434]
We had to revert it while we figure it out. Narrowed down that it returns a 503.

**Comment by da3dsoul** [comment]
Making progress. Now just 404, so likely a mapping issue

**Comment by bigretromike** [comment]
It work fine, if we are talking about /api/image/ as you need also to add apikey to get most of information out of Nancy Api.

**Comment by bigretromike** [comment]
Also remamber there were redundant EntryPoints for same functionality in old API.
It was JMMServerImage nad JMMServerRest - Rest part work fine without API

**Comment by da3dsoul** [comment]
JMMServerImage that desktop uses. So legacy yes.

**Comment by bigretromike** [comment]
I will fix it then

On October 6, 2016 4:46:52 PM GMT+02:00, da3dsoul <notifications@github.com> wrote:
>JMMServerImage that desktop uses. So legacy yes.
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/japanesemediamanager/jmmserver/issues/434#issuecomment-251985164

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bigretromike** [comment]
Oh yeah, Nancy dont do /jmmserverimage its still handle the old way ;-)
And The old one dont work after comenting out because of lack of acl ;-)

**Comment by bigretromike** [comment]
Also JMMServerImage is deprecated as it use byte arrays instead of real images

**Comment by bigretromike** [comment]
It strange how Nancy conflict with Nancy on same path... 
If both worked call never enter nancy and end up with code 400 (bad request)
but if you comment out nancy you get 502 ```The connection to '127.0.0.1' failed. <br />Error: ConnectionRefused (0x274d). <br />System.Net.Sockets.SocketException``` as it looks like acl is needed - but running it as Admin end up with 400 anyway so something went wrong with jmmserverimage anyway, cant we move to jmmserverrest ? as we moving anyway out of binary blobs?

**Comment by da3dsoul** [comment]
Currently ma3 and jmm desktop use it. If you want to port desktop to use it @netsplite can probably do ma3

**Comment by bigretromike** [comment]
ok I made it work 
(nancy side) but it has 2 in name

**Comment by bigretromike** [comment]
I can try with JMMD

**Comment by bigretromike** [comment]
What images are using via JMMServerImage in JMMD anyway ? I change all paths to invalid one and I still see images in JMMD

**Comment by bigretromike** [comment]
https://github.com/japanesemediamanager/jmmclient/issues/472 This one is related.

**Comment by bigretromike** [comment]
Ok, JMMServerImage is for downloading external images via jmmserver and send them to jmmd... strange but its how its made

**Comment by bigretromike** [comment]
JMMServerImage is still WCF thing - untill all client are moved. Until then JMMD was updated to use JMMServerImage2 (Legacy Nancy implementation of JMMServerImage)
@RickDB could you migrate from it to ?

**Comment by RickDB** [comment]
@bigretromike will need to look at the implementation but that will probably be for post 3.7 :)

**Comment by bigretromike** [comment]
No problem 

On October 6, 2016 8:35:04 PM GMT+02:00, Rick164 <notifications@github.com> wrote:
>@bigretromike will need to look at the implementation but that will
>probably be for post 3.7 :)
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/japanesemediamanager/jmmserver/issues/434#issuecomment-252050452

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by RickDB** [comment]
Looked at how we do it in JMMClient now (JMMServerImage2) and should be able to do it the same for some small differences, will give it a go here.

**Comment by RickDB** [comment]
Copied code over and adapted but server only seems to be returning 0 byte images using latest master branch, does it work ok in JMMClient?

**Comment by bigretromike** [comment]
If it teturn 0 byte 200 http code image then its blank image because server have image inside db but not on hdd. 

On October 6, 2016 9:58:54 PM GMT+02:00, Rick164 <notifications@github.com> wrote:
>Copied code over and adapted but server only seems to be returning 0
>byte images using latest master branch, does it work ok in JMMClient?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/japanesemediamanager/jmmserver/issues/434#issuecomment-252071728

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
Try the rest version of the image, pretty sure it works there

**Comment by bigretromike** [comment]
Both works as i tested both in fiddler , when the http code is 200 (valid command) and bytes are 0 its blankimage fix that i introduce for corrupted/missing images in db on server, but if http code respond aint 200 then its something else 

On October 7, 2016 6:33:27 AM GMT+02:00, da3dsoul <notifications@github.com> wrote:
>Try the rest version of the image, pretty sure it works there
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/japanesemediamanager/jmmserver/issues/434#issuecomment-252150817

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
Mk

**Comment by RickDB** [comment]
Checked and all files exist on server, all of the image files it retrieves via JMMServerImage2 (3000 or so) are 0 byte images at the moment.
When reverting client and server back to JMMServerImage (WCF) those get fetched correctly,, could be something on the client code but that looks fine when comparing it with JMMClient.

Not sure how to fix this at the moment so would probably need some pointers :)

**Comment by da3dsoul** [comment]
I got 404's so farther than I got. But I can check and see

**Comment by hidden4003** [comment]
Client migration is planned to happen on separate branch, 3.7 has to support the v1 API, so please revert it.

**Comment by bigretromike** [comment]
Wasnt it target as 3.7? If no, my bad. 
How you guys test it if one got 0 byte and other get 404?

On October 7, 2016 10:16:26 AM GMT+02:00, hidden4003 <notifications@github.com> wrote:
>Client migration is planned to happen on separate branch, 3.7 has to
>support the v1 API, so please revert it.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/japanesemediamanager/jmmserver/issues/434#issuecomment-252180021

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by da3dsoul** [comment]
The 404's were when I was working on it. Haven't tried in awhile. Unit testing and debugger contextual execution is how you check

**Comment by bigretromike** [comment]
I check it with both debug and fiddler 

On October 7, 2016 11:00:26 AM GMT+02:00, da3dsoul <notifications@github.com> wrote:
>The 404's were when I was working on it. Haven't tried in awhile. Unit
>testing and debugger contextual execution is how you check
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/japanesemediamanager/jmmserver/issues/434#issuecomment-252188413

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bigretromike** [comment]
@hidden4003 also to fix JMMServerImage from Nancy we need to migrate client as Nancy wont send blob information as its not design to. And this was not migration of client as migration is targeted for /bin api route;
I don't see the problem here as its only in 2 places that JMMServerImage is ever used... and that would give us oportunity to clean up JMMServerImage_Service out of JMMServer. and propably free up some resources

**Comment by bigretromike** [comment]
Also It looks like jmmserver is deleting images when trying to access it...

**Comment by bigretromike** [comment]
thats why /jmmserverimage2/ return 500 as there is missing image from server..

**Comment by bigretromike** [comment]
Im investing it

**Comment by bigretromike** [comment]
When both client and server use same image path client wipe out images resulting in error 500 on client side - as the stream was null.

As the initial path was revert im leaving this as information for later.

**Comment by bigretromike** [comment]
There is a JMMD bug that make this deletion things. I will add it to issue.

And close this issue with: https://github.com/japanesemediamanager/jmmserver/commit/13d1ad8c166c6b480b557f8ad3c22918dba0aaa6 as for now
