### ISSUE TITLE
Trakt not acting properly

### ISSUE THREAD

**Issue by Blackdixxa** [japanesemediamanager/jmmserver#436]
Hi all,

I've noticed a strange issue recently. 
When using the trakt sync button on JMM Server, it sync every single anime I have as watched even if I haven't played the serie yet.

ElementalCrisis confirmed the error.

**Comment by RickDB** [comment]
Hi @Blackdixxa 

One problem found and applied fix, it before assumed that if you had a file for an episode it would mean it was watched (not sure why).

Will test here as this is one of those bugs we have to be careful as like you noticed it will mess up your Trakt collection with not easy way to revert them online,

**Comment by Blackdixxa** [comment]
I used this technique to remove any duplicate http://huere.net/trakt/duplicate_removal/
but I still had to remove manually show I had not seen

**Comment by RickDB** [comment]
Tested with @Blackdixxa and indeed fixed.
