### ISSUE TITLE
Cloud Upload folder?

### ISSUE THREAD

**Issue by AreFinstad** [japanesemediamanager/jmmserver#438]
cloud uploading can be slow depending on the tools you use. 
JMM could do it i think while it hashes and syncs hash with the cache and clears out local space.

so normal folder, let JMM Hash and sync the hash. 
upload the file (one file at a time?), check hash on upload completion.
if hash is correct then automatically delete local file to just have a cloud version.

on completion it should start an import on that cloud folder we uploaded too (moving it out of its source folder and so on) 

this way we will not have to use slower tools to upload anime, do not have to wait for files to sync up if you are not in sync. and it would upload only one file at a time so it would clear local space alot quicker!

**Comment by maxpiva** [comment]
Hmm, believe or not upload to the cloud is not an easy task, the pipeline to do it right requires a lot of work, more on some cloud like amazon that do not support resume yet. Will think about when the cloud middleware has an stable upload, this feature at the first glance, its out of scope of the JMM, there is already tools to do just that.
