### ISSUE TITLE
Using Mapped drive or UNC path in import folder fails import

### ISSUE THREAD

**Issue by RickDB** [japanesemediamanager/jmmserver#440]
**Issue**

When using an existing or new import folder with an UNC path it will not import and reports folder doesn't exist.
Last time confirmed working by user is on commit id ba79932aa937d42e28ae2429fbb9383e50daf1b9

**To reproduce**

Add an UNC share the user has access to and run full import.

**Comment by RickDB** [comment]
Workaround added but still needs a better fix as it's related to the NutzCode filesystem resolver which at the moment doesn't handle network mappings or UNC paths.

**Comment by maxpiva** [comment]
Fixed on master
