### ISSUE TITLE
Certain Files Fail During Hashing

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/jmmserver#452]
When attempting to move select files from Drop Source to Drop Destination, these files fail and produce the following error

``[2016-09-28 21:18:10:333] Error|CommandRequest_HashFile.ProcessCommand => CommandRequest_HashFile.ProcessFile_LocalInfo => VideoLocal_Place.RefreshMediaInfo Unable to read the media information of file E:\Test\Ace of Diamond\Ace of the Diamond - 01 - The One Pitch [Commie].mkv ERROR: System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at JMMServer.Entities.VideoLocal_Place.RefreshMediaInfo() in D:\My Files\Documents\GitHub\jmmserver\JMMServer\Entities\VideoLocal_Place.cs:line 110``

![5628cf2c-2bbb-469d-adb7-6ffed4943059](https://cloud.githubusercontent.com/assets/9443295/18970603/b6efa3f6-8646-11e6-8a5c-4fec52cfb882.png)

**Comment by ElementalCrisis** [comment]
File Export.
[Ace_of_Diamond_mediainfo.txt](https://github.com/japanesemediamanager/jmmserver/files/501656/Ace_of_Diamond_mediainfo.txt)

**Comment by RickDB** [comment]
Added some validation to the double mentioned in error log, should handle the error not the cause as that is most likely:

- Mediainfo library we use is outdated or parsing the file wrong
- Error occured during readouts where it wasn't possible to get this value (file not found / locked etc..)

**Comment by maxpiva** [comment]
RIckDB already fixed it (If mediainfo return null, or empty, or whatever, value will be 0), seems a mediainfo issue, since i used your exact Anime, and all doubles returned fine.
