### ISSUE TITLE
ReplaceSchemaHost fails with Nancy

### ISSUE THREAD

**Issue by da3dsoul** [japanesemediamanager/jmmserver#455]
ServerURL works, so idk what's up with it.

**Comment by da3dsoul** [comment]
Figured it out the reason. The URLs are stored in the contract already replaced with 127.0.0.1

**Comment by maxpiva** [comment]
replace scheme host, will use the host asked by the request, as the base
host for server urls. Why is that...
Example:

If you ask for http://localhost:8111/XXX/XXX the returned links (keys,
images, etc), start with http://localhost:8111
But
if you asked for http://192.168.1.8/XXX/xXX the returned links are pointed
to 192.168.1.9
In the same way if you ask for it with the external ip, the return urls
inside the content will have the external ip.

I use WCF information, to obtain the requested host, and replace all links
with ReplaceSchameHost...
A Nancy compatible way should be made for that prupose.

**Comment by da3dsoul** [comment]
Because the contracts were generated with request not null. I probably fixed this just now, but more testing is needed.

**Comment by da3dsoul** [comment]
Yep fixed. It would get set when you issue a request, and not get unset until restart, so any contracts generated between would have it rewritten to the URL of the last request.
