### ISSUE TITLE
Rating in MediaContainer use both seperators

### ISSUE THREAD

**Issue by bigretromike** [japanesemediamanager/jmmserver#464]
Dexil provided log that show that JMM return XML with both commas and dots as rating seperators
```
rating="6,8"
rating="6.1"
```
This is in 3.6.1.0

**Comment by da3dsoul** [comment]
Idk how Kodi handles that, but it seems like it might cause issues

**Comment by bigretromike** [comment]
i fixed it on nakamori side
will push

**Comment by bigretromike** [comment]
This issue was on dutch os settings.
