### ISSUE TITLE
Naruto OVA linked wrong

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/jmmserver#47]
**Reported by akinci.d, Feb 20, 2013**

*What steps will reproduce the problem?*
1. I downloaded "Naruto Narutimate Hero 3: Finally a Clash! Jonin VS Genin!! Indescriminate Grand Melee Tournament Meeting!!" and the file got added in JMM

*What is the expected output? What do you see instead?*
Expected output: file being added to "Naruto Narutimate Hero 3: Finally a Clash! Jonin VS Genin!! Indescriminate Grand Melee Tournament Meeting!!" and find the episode there.

What I see instead:

1. When I click on the series (a9685) I can't find the episode, although it's showing up on the "Series info" but not on the "Episodes" tab. AniDB shows that file is added to storage.

2. On the dashboard the file seems to be linked to "Naruto 1-OVA" but when I enter the "Naruto" group, the episode isn't there.

3. Jmm says I have a file missing from the release groups I'm collecting (which isn't true).

**Comment by ElementalCrisis** [comment]
Just checked, the OVA shows up fine under it's own series and is apart of the Naruto group. Maybe something happen when originally hashed or some error when pulling the data from AniDB.
