### ISSUE TITLE
New status for checking hashes

### ISSUE THREAD

**Issue by da3dsoul** [japanesemediamanager/jmmserver#474]
Currently, on run import, it queues every file in the db and checks if it needs to be hashed (and skips most). It does say it is "Hashing File: ...", though. That is confusing, so we should add a status for "Checking File for Hashes: ..." and then change it if the file is actually hashing to "Hashing File: ..."

**Comment by da3dsoul** [comment]
@ElementalCrisis this will save a hundred bug reports, considering even the devs and alpha testers were confused.

**Comment by ElementalCrisis** [comment]
Agreed, it's very misleading.
