### ISSUE TITLE
Adding option (command) to rehash entire collection

### ISSUE THREAD

**Issue by t0815** [japanesemediamanager/jmmserver#483]
hi there,

not sure if that has been requested before. I think it would be a good thing, if we could rehash our entire collection and match it against stored hashes (of course for once recognized files only).

That way, we could find damaged files and could take action to redownload them.

**Comment by ElementalCrisis** [comment]
It's already been added and is apart of the 3.7 update for JMM Server. 

We offer daily builds which you can try, http://jmediamanager.org/latestdownloads/daily/, its the Integrity Check tool.

**Comment by da3dsoul** [comment]
Haha gotta love it when that happens

**Comment by t0815** [comment]
oh sry! But nice to hear :D
