### ISSUE TITLE
[DEV/BETA] Local video filenames empty after schema patch

### ISSUE THREAD

**Issue by t0815** [japanesemediamanager/jmmserver#488]
hi,

just noticed that current DEV/master schema patch does not update the new column 'FileName', leaving it empty after droping previous column 'FilePath'.  

This results in all local files being 'empty'.

<code>
new DatabaseCommand(54, 2, "ALTER TABLE `VideoLocal` ADD `FileName` text character set utf8 NOT NULL"),

new DatabaseCommand(54, 3, "ALTER TABLE `VideoLocal` ADD `VideoCodec` varchar(100) NOT NULL DEFAULT ''"),

new DatabaseCommand(54, 4, "ALTER TABLE `VideoLocal` ADD `VideoBitrate` varchar(100) NOT NULL DEFAULT ''"),

new DatabaseCommand(54, 5, "ALTER TABLE `VideoLocal` ADD `VideoBitDepth` varchar(100) NOT NULL DEFAULT ''"),

new DatabaseCommand(54, 6, "ALTER TABLE `VideoLocal` ADD `VideoFrameRate` varchar(100) NOT NULL DEFAULT ''"),

new DatabaseCommand(54, 7, "ALTER TABLE `VideoLocal` ADD `VideoResolution` varchar(100) NOT NULL DEFAULT ''"),

new DatabaseCommand(54, 8, "ALTER TABLE `VideoLocal` ADD `AudioCodec` varchar(100) NOT NULL DEFAULT ''"),

new DatabaseCommand(54, 9, "ALTER TABLE `VideoLocal` ADD `AudioBitrate` varchar(100) NOT NULL DEFAULT ''"),

new DatabaseCommand(54, 10, "ALTER TABLE `VideoLocal` ADD `Duration` bigint NOT NULL DEFAULT 0"),

new DatabaseCommand(54, 11,"INSERT INTO `VideoLocal_Place` (`VideoLocalID`, `FilePath`, `ImportFolderID`, `ImportFolderType`) SELECT `VideoLocalID`, `FilePath`, `ImportFolderID`, 1 as `ImportFolderType` FROM `VideoLocal`"),

new DatabaseCommand(54, 12, "ALTER TABLE `VideoLocal` DROP COLUMN `FilePath`"),`
</code>

**Comment by maxpiva** [comment]
You right seems, mysql is missing the videoinfo migration...

UPDATE VideoLocal SET VideoLocal.FileName=VideoInfo.FileName, VideoLocal.VideoCodec=VideoInfo.VideoCodec, VideoLocal.VideoBitrate=VideoInfo.VideoBitrate, VideoLocal.VideoBitDepth=VideoInfo.VideoBitDepth, VideoLocal.VideoFrameRate=VideoInfo.VideoFrameRate,VideoLocal.VideoResolution=VideoInfo.VideoResolution,VideoLocal.AudioCodec=VideoInfo.AudioCodec,VideoLocal.AudioBitrate=VideoInfo.AudioBitrate, VideoLocal.Duration=VideoInfo.Duration FROM VideoLocal INNER JOIN VideoInfo ON VideoLocal.Hash=VideoInfo.Hash

**Comment by da3dsoul** [comment]
I don't recommend regenerating videolocal. It takes forever. We might need a little patch function to only update that.

**Comment by maxpiva** [comment]
You suggest we add the above command in the update 54, then we add fix videolocal at the end of the mysql updates, which get the media information from media, and FileName from VideoLocal_Place and reconstruct?

**Comment by da3dsoul** [comment]
Basically, just fetch the already generated videolocal and add the place in filename.

**Comment by t0815** [comment]
Yea, but you will need to extract filename, since the original field could have sub-folders. New Field seems to require only Filename.

**Comment by t0815** [comment]
Tested, but there is one thing to consider.

Field 'FileName' in Table 'videolocal' expects ONLY the filename itself. Value stored in the field now contains the subfolder.

Field 'FilePath' in 'videolocal_place' already contains the filepath.

Solution would be something like this:

<code>
UPDATE `videolocal` v SET v.FileName = ( SELECT SUBSTR(vp.FilePath FROM POSITION('\\' IN vp.FilePath) + 1 FOR LENGTH(vp.FilePath)) FROM videolocal_place vp WHERE vp.VideoLocalID = v.VideoLocalID ) 

</code>

Not 100% working, since it does not handle more than 1 subfolder.

**Comment by t0815** [comment]
Tested, but there is once thing to consider.

Field 'videolocal.FileName' does only require the filename itself.
Value for 'videolocal.FileName' now contains subfolders.

Value for new field 'FilePath' in videolocal_place already contains the subfolder.
This results in FileNames being displayed incorrect.

You probably need something like this:

<code>
UPDATE `videolocal` v SET v.FileName = ( SELECT SUBSTR(vp.FilePath FROM POSITION('\\' IN vp.FilePath) + 1 FOR LENGTH(vp.FilePath)) FROM videolocal_place vp WHERE vp.VideoLocalID = v.VideoLocalID ) 
</code>

This is NOT 100% working, since it does only handle subfolder depth of 1. I only used this to fix the the Filename AFTER the already deleted field in videolocal table.
(I just did run the command multiple times to handle more than 1 subfolder)

To demonstrate this:
Value for videolocal_place.FilePath' now is "Asura Cryin\[Chihiro]_Asura_Cryin_-_01_[1280x720_H.264_AAC][6F91D254].mkv"

Value for videolocal.FileName is "Asura Cryin\[Chihiro]_Asura_Cryin_-_01_[1280x720_H.264_AAC][6F91D254].mkv" too. This results in wrong FileNames. Altho as it seems only displayed filenames seem to be wrong. The file is still playable. I will test this furhter.

**Comment by maxpiva** [comment]
Did you check that at the end there is a databasefix.

```
 public static void FixEmptyVideoInfos()
        {
            List<VideoLocal> locals = RepoFactory.VideoLocal.GetAll().Where(a => string.IsNullOrEmpty(a.FileName)).ToList();
            foreach (VideoLocal v in locals)
            {
                VideoLocal_Place p = v.Places.OrderBy(a => a.ImportFolderType).FirstOrDefault();
                if (p != null && !string.IsNullOrEmpty(p.FilePath) && v.Media != null)
                {
                    **v.FileName = p.FilePath;
                    int a=p.FilePath.LastIndexOf("\\",StringComparison.InvariantCulture);
                    if (a > 0)
                        v.FileName = p.FilePath.Substring(a + 1);**
                    VideoLocal_Place.FillVideoInfoFromMedia(v,v.Media);
                    RepoFactory.VideoLocal.Save(v,false);
                }
            }
        }

```
Is this not working?

**Comment by t0815** [comment]
hmm, this is strange. Yea, i did check after patch of course.
Here is what it looks like in client:

![image](https://cloud.githubusercontent.com/assets/10379828/19626966/504dfddc-993d-11e6-833d-a4b86cfb9933.png)

**Comment by t0815** [comment]
Ok, i did add a breakpoint and did debug the code. As it turns out, debugger didnt stop within the 'DatabaseFixes.FixEmptyVideoInfos' function. As it seems, app doesnt go in there.

**Comment by maxpiva** [comment]
Please check, the versions table in the database, delete version row 58.1, and also set filename to null in the database. That will make the databasefix run again.

**Comment by t0815** [comment]
yea i will check that now. Of course i always deleted all tables, and restored my backup SQL from version 3.6.1.0 prior testing this. So it should be working. Really strange. I double check DB and all now, just to be sure.

**Comment by maxpiva** [comment]
Hmm, if you restored, it should run. Gonna check...

**Comment by maxpiva** [comment]
Yup seems about right, please restore db, then put a breakpoint in FixEmptyVideoInfos.

**Comment by t0815** [comment]
this is really strange... just to be sure, i did add breakpoint in other database-fix functions, but the debugger won't go in there at all. Not sure if it's just Visual Studio acting up. As it seems, the FixEmptyVideoInfos() function is never executed. I did add breakpoint in public class DatabaseCommand ->  DatabaseCommand(int version, int revision, Action databasefix) constructor. And the command is created and added to the list just not executed it seems

**Comment by maxpiva** [comment]
Okey, go to DatabaseFactory Line 99. Put a breakpoint in there.  Instance.ExecuteDatabaseFixes();
When hit press F11. And check if the list of the fixes includes 
FixEmptyVideoInfos
Thanks

**Comment by t0815** [comment]
ok, looks like i found the problem:

<code>
 try
                {
                    Instance.CreateAndUpdateSchema();
                    RepoFactory.Init();
                    Instance.ExecuteDatabaseFixes();
                    Instance.PopulateInitialData();
                }
                catch (DatabaseCommandException e)
...
</code>

I'm not sure, but it seems the repo cache is created BEFORE the patches are being applied to db. So maybe data is inconsistent. Or an exception is happening within repo function. I will leave it, recreating repo and see what happens (debugger running and breakpoint)

As i see it now, the code only reaches till <code>RepoFactory.Init();</code> 
  <code> 
  Instance.ExecuteDatabaseFixes();
   Instance.PopulateInitialData();
</code>

are not executed. But i could be wrong, will wait until repo is created.

**Comment by maxpiva** [comment]
But why FileName has the path, it shouldn't.  Your original VideoInfo.FileName should be move to VideoLocal.FileName, that Databasefix, if for people who updated like you, the database and have no backup. Check in your original Database, the value inside VideoInfo.FileName it should be moved to VideoLocal.Filename , Last time i checked VideoInfo.Filename should only have FileName on previous versions of the database.

**Comment by t0815** [comment]
hmm, this is strange then. I restored the backup and 'VideoInfo.FileName' does indeed contain the sub-folder:

![image](https://cloud.githubusercontent.com/assets/10379828/19627776/6f456d12-994f-11e6-8ee9-86b4df72f91f.png)

**Comment by t0815** [comment]
this is getting way too strange now. I will do the following now. I will revert to current stable version. Clear whole DB again and run Import. Then we will see, if data is stored previously without subfolder.

**Comment by t0815** [comment]
Ok, reverted to current stable version 3.6.1.0, deleted whole DataBase and did run an import again.
I did check VideoInfo.FileName and it still contains Subfolder

![image](https://cloud.githubusercontent.com/assets/10379828/19627863/6555919a-9951-11e6-94c1-b19e40035db0.png)


So i'm assuming, it should be the same for all users updating from current stable version.

**Comment by maxpiva** [comment]
Hmm, Thats the key issue. VideoInfo has the filepath in filename, wonder why. Any clue from other devs?

**Comment by t0815** [comment]
Tested, issue is resolved with your last commit.  :)

**Comment by monsieurtaco** [comment]
@t0815 I've been unable to open the "Utilities" tab in JMM Desktop 3.6.1.0 and get a null reference error each time:
`[2016-10-24 12:19:10:395] Error|MainWindow.DisplayMainTab => UnrecognisedVideos.RefreshUnrecognisedFiles => Utils.ShowErrorMessage System.NullReferenceException: Object reference not set to an instance of an object.
   at JMMClient.ViewModel.ImportFolderVM..ctor(Contract_ImportFolder contract) in D:\My Files\Documents\GitHub\jmmclient\JMMClient\ViewModel\ImportFolderVM.cs:line 88
   at JMMClient.ViewModel.VideoLocalVM..ctor(Contract_VideoLocal contract) in D:\My Files\Documents\GitHub\jmmclient\JMMClient\ViewModel\VideoLocalVM.cs:line 127
   at JMMClient.UserControls.UnrecognisedVideos.RefreshUnrecognisedFiles() in D:\My Files\Documents\GitHub\jmmclient\JMMClient\UserControls\UnrecognisedVideos.xaml.cs:line 844`

I can't say for sure this is related or what's causing this, just wanted to know if you have any insight on this.

**Comment by monsieurtaco** [comment]
Got the latest version of JMM Client from repo and it works great... I guess downloaded 3.6.1.0 version doesn't work with latest dev JMM, which shouldn't be too surprising.

**Comment by maxpiva** [comment]
Did you check that at the end there is a databasefix.

 public static void FixEmptyVideoInfos()
        {
            List<VideoLocal> locals =
RepoFactory.VideoLocal.GetAll().Where(a =>
string.IsNullOrEmpty(a.FileName)).ToList();
            foreach (VideoLocal v in locals)
            {
                VideoLocal_Place p = v.Places.OrderBy(a =>
a.ImportFolderType).FirstOrDefault();
                if (p != null && !string.IsNullOrEmpty(p.FilePath) &&
v.Media != null)
                {
                  *  v.FileName = p.FilePath;*
*                    int
a=p.FilePath.LastIndexOf("\\",StringComparison.InvariantCulture);*
*                    if (a > 0)*
*                        v.FileName = p.FilePath.Substring(a + 1);*
                    VideoLocal_Place.FillVideoInfoFromMedia(v,v.Media);
                    RepoFactory.VideoLocal.Save(v,false);
                }
            }
        }

Is this not working?

**Comment by t0815** [comment]
@monsieurtaco ; correct, current dev/master is not compatible with current stable version DB layout. You need to restore either a Backup prior to changes made by current DEV build or keep using dev/master build.
