### ISSUE TITLE
[master] Database Error

### ISSUE THREAD

**Issue by bigretromike** [japanesemediamanager/jmmserver#492]
![clipboard02](https://cloud.githubusercontent.com/assets/6052025/19635204/ed6a5074-99c0-11e6-8da6-0a0b10adbd12.jpg)

**Comment by bigretromike** [comment]
And YES - my db before updating have ```VideoInfo```

**Comment by bigretromike** [comment]
The problem is:
```
new DatabaseCommand(54, 18, "UPDATE `VideoLocal` INNER JOIN `VideoInfo` ON `VideoLocal`.`Hash`=`VideoInfo`.`Hash` SET `VideoLocal`.`FileName`=`VideoInfo`.`FileName`,`VideoLocal`.`VideoCodec`=`VideoInfo`.`VideoCodec`,`VideoLocal`.`VideoBitrate`=`VideoInfo`.`VideoBitrate`,`VideoLocal`.`VideoBitDepth`=`VideoInfo`.`VideoBitDepth`,`VideoLocal`.`VideoFrameRate`=`VideoInfo`.`VideoFrameRate`,`VideoLocal`.`VideoResolution`=`VideoInfo`.`VideoResolution`,`VideoLocal`.`AudioCodec`=`VideoInfo`.`AudioCodec`,`VideoLocal`.`AudioBitrate`=`VideoInfo`.`AudioBitrate`,`VideoLocal`.`Duration`=`VideoInfo`.`Duration`"),            
new DatabaseCommand(54, 19, "DROP TABLE `VideoInfo`"),
```

as my 54 in db end with 18 being DROP Table 'VideoInfo' 
I dunno why is that... just for the information to double check i will edit this by hand to it will update correctly

**Comment by t0815** [comment]
hm, but then the 54, 18 should fail already since it inner joins 'VideoInfo'. From what JMM -Server Version did you update? VideoInfo is current release DB Table and is used in current stable build too, so it should be there.

**Comment by bigretromike** [comment]
no, 54.18 was the in my case ```DROP Table VideoInfo``` which throw error as VideoInfo wasn't there any more.
Mine db was 57 before updating.

If you refer to current stable 3.6.1.0 I was doing this on current master 3.7.0.0

**Comment by t0815** [comment]
ah ok. Do you have a backup of your Database? You need to restore it, and then start jmmserver again. There was a bug in current DB update cycle, that has been fixed yesterday.

**Comment by bigretromike** [comment]
Yeah I already fix it. So this was added recently . I issue this so let people know that the "fix" made it throw up with error :-) 
From your information I now know that this was intention - and wont be reproduce on stable version.
