### ISSUE TITLE
Data stored inside PlexContractBlob in DB

### ISSUE THREAD

**Issue by bigretromike** [japanesemediamanager/jmmserver#494]
Looking thru db I found that some of the metadata related for ex. to episode are stored EXCLUSIVELY inside PlexContractBlob. 
As I fully understand the needed of this (and how this speed up Plex) and I would like to ask for storing those that data also in traditional way inside db.
Having data available without extracting them out of contractblob would be also great.

Is it possible @maxpiva ?

**Comment by da3dsoul** [comment]
We could, but it would be slower than extracting the blob. The values that aren't in the db but are in the blob are generated in Helper.Generate... and they would need to be regenerated rather than just unzipping them.

**Comment by bigretromike** [comment]
direct access via db or cache via RepoRactory.AnimeEpisode.GetByID(id).summary would be slower than unzipping blob ? also most of the time you dont have to regenerate values like ```sumary``` or example because its constant - you dont regenerate plexcontactblobs as it would require to connect to anidb as we dont have local copy of full content anyway.

**Comment by da3dsoul** [comment]
It depends. By 'regenerate' I mean rebuild the data into the same format. Summary is gotten from TvDB. You need to build a cross reference, calculate the episode number on TvDB vs AniDB, and then get the info from TvDB_Episode

**Comment by bigretromike** [comment]
hmm so it is in db then

**Comment by da3dsoul** [comment]
Yes just in an inconvenient place to access with an AniDB episode
