### ISSUE TITLE
Messed up urls in kodi

### ISSUE THREAD

**Issue by da3dsoul** [japanesemediamanager/jmmserver#502]
@bigretromike ....
```
  <Directory GenericId="439" key="http://127.0.0.1:8111/JMMServerKodi/api/GetMetadata/3/439" 
  <Directory GenericId="5202" key="http://127.0.0.1:8111/JMMServerKodi/api/GetMetadata/2/5202" 
  <Directory GenericId="5276" key="http://127.0.0.1:8111/JMMServerKodi/api/GetMetadata/2/5276"
```
Snipping to save space. That tells enough.
This ProperURL thing is certainly the cause, and I need breakfast.... Please fix it.

**Comment by bigretromike** [comment]
Sure... if its a problem but I dont recall adding it anywere else than apiv2

**Comment by bigretromike** [comment]
Which call you made to get that output ?

**Comment by bigretromike** [comment]
```
/api/filters/get
``` 
I see - im on it

**Comment by da3dsoul** [comment]
It happens with movies especially

**Comment by bigretromike** [comment]
it works ok, it worked same before we just didn't use api/filters/get ;-) its even in comments. I testing patch and will commit + a bit of speed up for both plex/kodi and apiv2 in constructing urls ;-)
