### ISSUE TITLE
Add support for MPExtended service

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/jmmserver#6]
Add support for MPExtended service

http://wiki.team-mediaportal.com/1_MEDIAPORTAL_1/17_Extensions/Remote_Access/MPExtended

http://wiki.team-mediaportal.com/1_MEDIAPORTAL_1/17_Extensions/Remote_Access/MPExtended/Developers

**Comment by ElementalCrisis** [comment]
This is no longer possible as the developer has restricted access.
