### ISSUE TITLE
Problems with Ginga Eiyuu Densetsu Gaiden (1999)

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/jmmserver#66]
**Reported by werndlymob, Jul 3, 2013**

Here is a bit of a strange one. JMM claims that I am missing one episode for Ginga Eiyuu Densetsu Gaiden (1999) but when I check the episode list they are all marked as available (btw there is a small spelling error in the UI, Episodes->Availability->No Files Aavailable).

I have the Central Anime release, used to have the LD/DVD version but now switched to the BD version but in both cases it claims that I am missing 1 episode while still showing all episodes as available.
There are no specials or anything either for it so I can't for my life understand what I am supposed to be missing.

http://forum.team-mediaportal.com/threads/my-anime-3.107475/page-52#post-1000107

**Comment by ElementalCrisis** [comment]
Pretty sure this was fixed in Version 3.4.6.2.
