### ISSUE TITLE
Clearing anidb queue causes ridiculous HDD usage

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/jmmserver#76]
**Reported by enlait, Jun 16, 2014**

*What steps will reproduce the problem?*

1. queue a lot of actions for anidb worker (eg: move anime to another folder. In fact, why does it even require to get file data from anidb again?)
2. attempt to clear queue

One would expect queue to be emptied in a reasonable time. Actions should not be removed from queue individually - they are stored in a damn database, it's optimized for manipulating data in bulk!
Instead, extreme mysql hdd activity suggests actions are removed one by one.

**Comment by maxpiva** [comment]
Closed, clear is fast now, Only one transaction
