### ISSUE TITLE
Too long of a path, files not hashed

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/jmmserver#78]
**Reported by themountain632, Aug 10, 2014**

*What steps will reproduce the problem?*

1. Create a file with a path longer then supported by windows
2. Hash Check fails

*What is the expected output? What do you see instead?*
No output and the file is missing in my list

*Please provide any additional information below.*
Utorrent allows files to be downloaded to paths longer then windows supports (without-end users knowledge) the end-user will only be aware that the file path is too long when they go to copy/delete/rename the file and get a parameter incorrect message. VLC/MPC-HC/ETC all play the file fine. However, JMM will not hash the file. Nor will any sort of warning be displayed to the end-user indicating that there is some sort of problem.

This needs to be error trapped and I have found numerous releases on Nyaa with unsupported paths.

**Comment by bigretromike** [comment]
If we want support those inside windows then maybe use 8dot3 paths ? but that need to be enabled in Windows.

**Comment by hidden4003** [comment]
According to https://github.com/dotnet/corefx/issues/645 it will be fixed eventually with a newer version of .NET, or the other way would be to make a wrapper to go through PInvoke and win32 api.

**Comment by ElementalCrisis** [comment]
I'd say add the temporary fix for now and a warning message in the log about the file path length.

**Comment by bigretromike** [comment]
@hidden4003 we don't use CoreFX, and this problems is currently ongoing also that fix of corefx is related to 8dot3 path translation

**Comment by hidden4003** [comment]
@bigretromike I know that we don't use CoreFX but last comment in the issue I linked says that it will appear in .NET sooner or later.

Then PInvoke for now and we'll figure linux part when it comes to that.

**Comment by bigretromike** [comment]
@hidden4003 Linux don't have that problem 👍

**Comment by hidden4003** [comment]
Checked with a very long path, now works.
