### ISSUE TITLE
Add Support for XBMC - Advanced Support

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/jmmserver#8]
This issue is to add second stage (advanced) support to XBMC.
This means actually creating a plugin for XBMC, and exposing JMM Server functionality via the rest interface

**Comment by jmediamanager** [comment]
Now called Kodi
http://kodi.wiki/view/Add-on_development

**Comment by anzerman** [comment]
would be keen for this :+1:

**Comment by ElementalCrisis** [comment]
Already done, https://github.com/bigretromike/nakamoriplugin

Issue will remain open until JMM update with Nakamori support is official.
