### ISSUE TITLE
Trakt sync issues

### ISSUE THREAD

**Issue by scythe000** [japanesemediamanager/jmmserver#99]
I've been dealing with an issue since 2012 apparently. MA3 syncs to Trakt. For Naruto and FMA, a few episodes will never properly mark as watched. I set them as watched in MA3, sync and the unmark. I go to Trakt, and they are marked as 'scrobbled' as opposed to all the other episodes which are marked as watched. I can see every time I set it as watched sync, but it just syncs as scrobbled, and MA3 dutifully grabs an unwatched status and the next sync. really, really annoying.

**Comment by jmediamanager** [comment]
I believe this is no longer an issues
